var mdcHorNav = new Array()
mdcHorNav[0] = new Object()
mdcHorNav[0].pIDs = "|2_3000|2_3002_asia|2_3002_europe|"
mdcHorNav[0].name = "Market Data<br/>Home"
mdcHorNav[0].href = "/redirect/marketsdata.html"
mdcHorNav[0].subnav = new Array();

mdcHorNav[1] = new Object()
mdcHorNav[1].pIDs = "|2_3002|"
mdcHorNav[1].name = "U.S. Stocks"
mdcHorNav[1].href = "/mdc/public/page/mdc_us_stocks.html"
mdcHorNav[1].subnav = new Array();
mdcHorNav[1].subnav[0] = new Object();
mdcHorNav[1].subnav[0].text = "Main: Indexes, Overview, Links to All Data"
mdcHorNav[1].subnav[0].href = "/mdc/public/page/mdc_us_stocks.html"
mdcHorNav[1].subnav[0].indent = 0;
mdcHorNav[1].subnav[0].style = "navmenupage";
mdcHorNav[1].subnav[0].changeBg = false;
mdcHorNav[1].subnav[1] = new Object();
mdcHorNav[1].subnav[1].text = "Most Actives, Gainers, Decliners"
mdcHorNav[1].subnav[1].indent = 0;
mdcHorNav[1].subnav[1].style = "navmenusec";
mdcHorNav[1].subnav[2] = new Array();
mdcHorNav[1].subnav[2] = new Object();
mdcHorNav[1].subnav[2].text = "Most Actives: NYSE, Nasdaq, Arca, Comp";
mdcHorNav[1].subnav[2].href = "/mdc/public/page/2_3021-activnyse-actives.html";
mdcHorNav[1].subnav[2].isHist = true;
mdcHorNav[1].subnav[2].indent = 0;
mdcHorNav[1].subnav[2].style = "navmenuitem";
mdcHorNav[1].subnav[3] = new Object();
mdcHorNav[1].subnav[3].text = "Gainers: NYSE, Nasdaq, Arca, Comp";
mdcHorNav[1].subnav[3].href = "/mdc/public/page/2_3021-gainnyse-gainer.html";
mdcHorNav[1].subnav[3].isHist = true;
mdcHorNav[1].subnav[3].indent = 0;
mdcHorNav[1].subnav[3].style = "navmenuitem";
mdcHorNav[1].subnav[4] = new Object();
mdcHorNav[1].subnav[4].text = "Decliners: NYSE, Nasdaq, Arca, Comp";
mdcHorNav[1].subnav[4].href = "/mdc/public/page/2_3021-losenyse-loser.html";
mdcHorNav[1].subnav[4].isHist = true;
mdcHorNav[1].subnav[4].indent = 0;
mdcHorNav[1].subnav[4].style = "navmenuitem";
mdcHorNav[1].subnav[5] = new Object();
mdcHorNav[1].subnav[5].text = "Volume Movers: NYSE, Nasdaq, Arca, Comp";
mdcHorNav[1].subnav[5].href = "/mdc/public/page/2_3021-volpctnyse-volumes.html";
mdcHorNav[1].subnav[5].isHist = true;
mdcHorNav[1].subnav[5].indent = 0;
mdcHorNav[1].subnav[5].style = "navmenuitem";
mdcHorNav[1].subnav[6] = new Object();
mdcHorNav[1].subnav[6].text = "New Highs & Lows: NYSE, Nasdaq, MKT, Arca";
mdcHorNav[1].subnav[6].href = "/mdc/public/page/2_3021-newhinyse-newhighs.html";
mdcHorNav[1].subnav[6].isHist = true;
mdcHorNav[1].subnav[6].indent = 0;
mdcHorNav[1].subnav[6].style = "navmenuitem";
mdcHorNav[1].subnav[7] = new Object();
mdcHorNav[1].subnav[7].text = "OTC Bulletin Board Most Actives";
mdcHorNav[1].subnav[7].href = "/mdc/public/page/2_3021-otcma.html";
mdcHorNav[1].subnav[7].indent = 0;
mdcHorNav[1].subnav[7].style = "navmenuitem";
mdcHorNav[1].subnav[8] = new Object();
mdcHorNav[1].subnav[8].text = "Industries/Sectors"
mdcHorNav[1].subnav[8].indent = 0;
mdcHorNav[1].subnav[8].style = "navmenusec";
mdcHorNav[1].subnav[9] = new Object();
mdcHorNav[1].subnav[9].text = "All Industries: Intraday Performance";
mdcHorNav[1].subnav[9].href = "/public/npage/all_industries.html";
mdcHorNav[1].subnav[9].indent = 0;
mdcHorNav[1].subnav[9].style = "navmenuitem";
mdcHorNav[1].subnav[10] = new Object();
mdcHorNav[1].subnav[10].text = "Leading &amp; Lagging Industries: Intraday";
mdcHorNav[1].subnav[10].href = "/mdc/public/page/2_3024-djleadlag.html";
mdcHorNav[1].subnav[10].indent = 0;
mdcHorNav[1].subnav[10].style = "navmenuitem";
mdcHorNav[1].subnav[11] = new Object();
mdcHorNav[1].subnav[11].text = "Industry Group Tracker";
mdcHorNav[1].subnav[11].href = "/public/npage/industry_grp_center.html";
mdcHorNav[1].subnav[11].indent = 0;
mdcHorNav[1].subnav[11].style = "navmenuitem";
mdcHorNav[1].subnav[12] = new Object();
mdcHorNav[1].subnav[12].text = "Map of the Market: Intraday Performance by Sector";
mdcHorNav[1].subnav[12].href = "/mdc/public/page/2_3024-markets_map_of_the_market.html";
mdcHorNav[1].subnav[12].indent = 0;
mdcHorNav[1].subnav[12].style = "navmenuitem";
mdcHorNav[1].subnav[13] = new Object();
mdcHorNav[1].subnav[13].text = "Sector Map: Basic Materials";
mdcHorNav[1].subnav[13].href = "/mdc/public/page/2_3024-sm_basic_materials_map.html";
mdcHorNav[1].subnav[13].indent = 1;
mdcHorNav[1].subnav[13].style = "navmenuitem";
mdcHorNav[1].subnav[14] = new Object();
mdcHorNav[1].subnav[14].text = "Sector Map: Consumer, Cyclical";
mdcHorNav[1].subnav[14].href = "/mdc/public/page/2_3024-sm_consumer_cyclical_map.html";
mdcHorNav[1].subnav[14].indent = 1;
mdcHorNav[1].subnav[14].style = "navmenuitem";
mdcHorNav[1].subnav[15] = new Object();
mdcHorNav[1].subnav[15].text = "Sector Map: Consumer, Non-Cyclical";
mdcHorNav[1].subnav[15].href = "/mdc/public/page/2_3024-sm_consumer_noncyclical_map.html";
mdcHorNav[1].subnav[15].indent = 1;
mdcHorNav[1].subnav[15].style = "navmenuitem";
mdcHorNav[1].subnav[16] = new Object();
mdcHorNav[1].subnav[16].text = "Sector Map: Energy";
mdcHorNav[1].subnav[16].href = "/mdc/public/page/2_3024-sm_energy_map.html";
mdcHorNav[1].subnav[16].indent = 1;
mdcHorNav[1].subnav[16].style = "navmenuitem";
mdcHorNav[1].subnav[17] = new Object();
mdcHorNav[1].subnav[17].text = "Sector Map: Financial";
mdcHorNav[1].subnav[17].href = "/mdc/public/page/2_3024-sm_financial_map.html";
mdcHorNav[1].subnav[17].indent = 1;
mdcHorNav[1].subnav[17].style = "navmenuitem";
mdcHorNav[1].subnav[18] = new Object();
mdcHorNav[1].subnav[18].text = "Sector Map: Health Care";
mdcHorNav[1].subnav[18].href = "/mdc/public/page/2_3024-sm_healthcare_map.html";
mdcHorNav[1].subnav[18].indent = 1;
mdcHorNav[1].subnav[18].style = "navmenuitem";
mdcHorNav[1].subnav[19] = new Object();
mdcHorNav[1].subnav[19].text = "Sector Map: Industrial";
mdcHorNav[1].subnav[19].href = "/mdc/public/page/2_3024-sm_industrial_map.html";
mdcHorNav[1].subnav[19].indent = 1;
mdcHorNav[1].subnav[19].style = "navmenuitem";
mdcHorNav[1].subnav[20] = new Object();
mdcHorNav[1].subnav[20].text = "Sector Map: Technology";
mdcHorNav[1].subnav[20].href = "/mdc/public/page/2_3024-sm_technology_map.html";
mdcHorNav[1].subnav[20].indent = 1;
mdcHorNav[1].subnav[20].style = "navmenuitem";
mdcHorNav[1].subnav[21] = new Object();
mdcHorNav[1].subnav[21].text = "Sector Map: Telecom";
mdcHorNav[1].subnav[21].href = "/mdc/public/page/2_3024-sm_telecomm_map.html";
mdcHorNav[1].subnav[21].indent = 1;
mdcHorNav[1].subnav[21].style = "navmenuitem";
mdcHorNav[1].subnav[22] = new Object();
mdcHorNav[1].subnav[22].text = "Sector Map: Utilities";
mdcHorNav[1].subnav[22].href = "/mdc/public/page/2_3024-sm_utility_map.html";
mdcHorNav[1].subnav[22].indent = 1;
mdcHorNav[1].subnav[22].style = "navmenuitem";
mdcHorNav[1].subnav[23] = new Object();
mdcHorNav[1].subnav[23].columnBreak = true;
mdcHorNav[1].subnav[24] = new Object();
mdcHorNav[1].subnav[24].text = "Stock Scan & Ways to Invest";
mdcHorNav[1].subnav[24].indent = 0;
mdcHorNav[1].subnav[24].style = "navmenusec";
mdcHorNav[1].subnav[25] = new Object();
mdcHorNav[1].subnav[25].text = "Dividend Stocks";
mdcHorNav[1].subnav[25].href = "/mdc/public/page/2_3022-scandiv.html";
mdcHorNav[1].subnav[25].isHist = true;
mdcHorNav[1].subnav[25].indent = 0;
mdcHorNav[1].subnav[25].style = "navmenuitem";
mdcHorNav[1].subnav[26] = new Object();
mdcHorNav[1].subnav[26].text = "Growth Stocks";
mdcHorNav[1].subnav[26].href = "/mdc/public/page/2_3022-scangrowth.html";
mdcHorNav[1].subnav[26].indent = 0;
mdcHorNav[1].subnav[26].style = "navmenuitem";
mdcHorNav[1].subnav[27] = new Object();
mdcHorNav[1].subnav[27].text = "Large Stocks";
mdcHorNav[1].subnav[27].href = "/mdc/public/page/2_3022-scanlarge.html";
mdcHorNav[1].subnav[27].indent = 0;
mdcHorNav[1].subnav[27].style = "navmenuitem";
mdcHorNav[1].subnav[28] = new Object();
mdcHorNav[1].subnav[28].text = "MidCap Stocks";
mdcHorNav[1].subnav[28].href = "/mdc/public/page/2_3022-scanmid.html";
mdcHorNav[1].subnav[28].indent = 0;
mdcHorNav[1].subnav[28].style = "navmenuitem";
mdcHorNav[1].subnav[29] = new Object();
mdcHorNav[1].subnav[29].text = "Small Stocks";
mdcHorNav[1].subnav[29].href = "/mdc/public/page/2_3022-scansmall.html";
mdcHorNav[1].subnav[29].indent = 0;
mdcHorNav[1].subnav[29].style = "navmenuitem";
mdcHorNav[1].subnav[30] = new Object();
mdcHorNav[1].subnav[30].text = "";
mdcHorNav[1].subnav[30].href = "";
mdcHorNav[1].subnav[30].indent = 0;
mdcHorNav[1].subnav[30].style = "";
mdcHorNav[1].subnav[31] = new Object();
mdcHorNav[1].subnav[31].text = "Value Stocks";
mdcHorNav[1].subnav[31].href = "/mdc/public/page/2_3022-scanvalue.html";
mdcHorNav[1].subnav[31].indent = 0;
mdcHorNav[1].subnav[31].style = "navmenuitem";
mdcHorNav[1].subnav[32] = new Object();
mdcHorNav[1].subnav[32] = new Object();
mdcHorNav[1].subnav[32].text = "Analysts' Ratings Changes";
mdcHorNav[1].subnav[32].indent = 0;
mdcHorNav[1].subnav[32].style = "navmenusec";
mdcHorNav[1].subnav[33] = new Object();
mdcHorNav[1].subnav[33].text = "Upgrades & Downgrades";
mdcHorNav[1].subnav[33].href = "/mdc/public/page/2_3024-UpgradesDowngrades.html";
mdcHorNav[1].subnav[33].indent = 0;
mdcHorNav[1].subnav[33].style = "navmenuitem";
mdcHorNav[1].subnav[34] = new Object();
mdcHorNav[1].subnav[34].text = "Money Flows";
mdcHorNav[1].subnav[34].indent = 0;
mdcHorNav[1].subnav[34].style = "navmenusec";
mdcHorNav[1].subnav[35] = new Object();
mdcHorNav[1].subnav[35].text = "Market & Sector Overview";
mdcHorNav[1].subnav[35].href = "/mdc/public/page/2_3022-mfsctrscan-moneyflow.html";
mdcHorNav[1].subnav[35].isHist = true;
mdcHorNav[1].subnav[35].indent = 0;
mdcHorNav[1].subnav[35].style = "navmenuitem";
mdcHorNav[1].subnav[36] = new Object();
mdcHorNav[1].subnav[36].text = "Selling on Strength";
mdcHorNav[1].subnav[36].href = "/mdc/public/page/2_3022-mflppg-moneyflow.html";
mdcHorNav[1].subnav[36].isHist = true;
mdcHorNav[1].subnav[36].hasCsv = true;
mdcHorNav[1].subnav[36].indent = 0;
mdcHorNav[1].subnav[36].style = "navmenuitem";
mdcHorNav[1].subnav[37] = new Object();
mdcHorNav[1].subnav[37].text = "Buying on Weakness";
mdcHorNav[1].subnav[37].href = "/mdc/public/page/2_3022-mfgppl-moneyflow.html";
mdcHorNav[1].subnav[37].isHist = true;
mdcHorNav[1].subnav[37].hasCsv = true;
mdcHorNav[1].subnav[37].indent = 0;
mdcHorNav[1].subnav[37].style = "navmenuitem";
mdcHorNav[1].subnav[38] = new Object();
mdcHorNav[1].subnav[38].text = "Index Analysis";
mdcHorNav[1].subnav[38].indent = 0;
mdcHorNav[1].subnav[38].style = "navmenusec";
mdcHorNav[1].subnav[39] = new Object();
mdcHorNav[1].subnav[39].text = "";
mdcHorNav[1].subnav[39].href = "/mdc/public/page/2_3047-djia_alltime.html";
mdcHorNav[1].subnav[39].indent = 0;
mdcHorNav[1].subnav[39].style = "navmenuitem";
mdcHorNav[1].subnav[40] = new Object();
mdcHorNav[1].subnav[40].text = "Charts of Major Indexes";
mdcHorNav[1].subnav[40].href = "/mdc/public/page/2_3024-charts.html";
mdcHorNav[1].subnav[40].indent = 0;
mdcHorNav[1].subnav[40].style = "navmenuitem";
mdcHorNav[1].subnav[41] = new Object();
mdcHorNav[1].subnav[41].text = "Dow Averages Hour by Hour";
mdcHorNav[1].subnav[41].href = "/mdc/public/page/2_3022-djiahourly.html";
mdcHorNav[1].subnav[41].indent = 0;
mdcHorNav[1].subnav[41].style = "navmenuitem";

mdcHorNav[1].subnav[42] = new Object();
mdcHorNav[1].subnav[42].text = "P/Es & Yields on Major Indexes";
mdcHorNav[1].subnav[42].href = "/mdc/public/page/2_3021-peyield.html";
mdcHorNav[1].subnav[42].indent = 0;
mdcHorNav[1].subnav[42].style = "navmenuitem";
mdcHorNav[1].subnav[43] = new Object();
mdcHorNav[1].subnav[43].text = "";
mdcHorNav[1].subnav[43].href = "/mdc/public/page/2_3047-indices_alltime.html";
mdcHorNav[1].subnav[43].indent = 0;
mdcHorNav[1].subnav[43].style = "navmenuitem";
mdcHorNav[1].subnav[44] = new Object();
mdcHorNav[1].subnav[44].text = "";
mdcHorNav[1].subnav[44].href = "";
mdcHorNav[1].subnav[44].indent = 0;
mdcHorNav[1].subnav[44].style = "";
mdcHorNav[1].subnav[45] = new Object();
mdcHorNav[1].subnav[45].text = "";
mdcHorNav[1].subnav[45].href = "";
mdcHorNav[1].subnav[45].indent = 0;
mdcHorNav[1].subnav[45].style = "";
mdcHorNav[1].subnav[46] = new Object();
mdcHorNav[1].subnav[46].columnBreak = true;
mdcHorNav[1].subnav[47] = new Object();
mdcHorNav[1].subnav[47].text = "Closing Indexes & Diaries";
mdcHorNav[1].subnav[47].indent = 0;
mdcHorNav[1].subnav[47].style = "navmenusec";
mdcHorNav[1].subnav[48] = new Object();
mdcHorNav[1].subnav[48].text = "Dow Jones U.S. TSM Indexes";
mdcHorNav[1].subnav[48].href = "/mdc/public/page/2_3022-djwilshire.html";
mdcHorNav[1].subnav[48].indent = 0;
mdcHorNav[1].subnav[48].style = "navmenuitem";
mdcHorNav[1].subnav[49] = new Object();
mdcHorNav[1].subnav[49].text = "Markets Diary";
mdcHorNav[1].subnav[49].href = "/mdc/public/page/2_3021-tradingdiary2.html";
mdcHorNav[1].subnav[49].isHist = true;
mdcHorNav[1].subnav[49].indent = 0;
mdcHorNav[1].subnav[49].style = "navmenuitem";
mdcHorNav[1].subnav[50] = new Object();
mdcHorNav[1].subnav[50].text = "Stock Indexes: Data Bank";
mdcHorNav[1].subnav[50].href = "/mdc/public/page/2_3022-usclosingstk.html";
mdcHorNav[1].subnav[50].isHist = true;
mdcHorNav[1].subnav[50].indent = 0;
mdcHorNav[1].subnav[50].style = "navmenuitem";
mdcHorNav[1].subnav[51] = new Object();
mdcHorNav[1].subnav[51].text = "Stocks & Trading Statistics";
mdcHorNav[1].subnav[51].indent = 0;
mdcHorNav[1].subnav[51].style = "navmenusec";
mdcHorNav[1].subnav[52] = new Object();
mdcHorNav[1].subnav[52].text = "Dividends";
mdcHorNav[1].subnav[52].href = "/mdc/public/page/2_3022-dividends.html";
mdcHorNav[1].subnav[52].isHist = true;
mdcHorNav[1].subnav[52].indent = 0;
mdcHorNav[1].subnav[52].style = "navmenuitem";
mdcHorNav[1].subnav[53] = new Object();
mdcHorNav[1].subnav[53].text = "Hedge Fund Benchmarks";
mdcHorNav[1].subnav[53].href = "/mdc/public/page/2_3022-hedgefndbnchmrk.html";
mdcHorNav[1].subnav[53].indent = 0;
mdcHorNav[1].subnav[53].style = "navmenuitem";

mdcHorNav[1].subnav[54] = new Object();
mdcHorNav[1].subnav[54].text = "Insider Trading Spotlight";
mdcHorNav[1].subnav[54].href = "/mdc/public/page/2_3023-insider.html";
mdcHorNav[1].subnav[54].indent = 0;
mdcHorNav[1].subnav[54].style = "navmenuitem";

mdcHorNav[1].subnav[55] = new Object();
mdcHorNav[1].subnav[55].text = "";
mdcHorNav[1].subnav[55].href = "";
mdcHorNav[1].subnav[55].indent = 0;
mdcHorNav[1].subnav[55].style = "";

mdcHorNav[1].subnav[56] = new Object();
mdcHorNav[1].subnav[56].text = "";
mdcHorNav[1].subnav[56].href = "/mdc/public/page/2_3024-oddlottrades.html";
mdcHorNav[1].subnav[56].indent = 0;
mdcHorNav[1].subnav[56].style = "navmenuitem";
mdcHorNav[1].subnav[57] = new Object();
mdcHorNav[1].subnav[57].text = "";
//mdcHorNav[1].subnav[57].href = "http://hosting.briefing.com/wsj/calendars/splits.htm";
//mdcHorNav[1].subnav[57].indent = 0;
mdcHorNav[1].subnav[57].style = "";
mdcHorNav[1].subnav[58] = new Object();
mdcHorNav[1].subnav[58].text = "After-Hours Trading";
mdcHorNav[1].subnav[58].indent = 0;
mdcHorNav[1].subnav[58].style = "navmenusec";
mdcHorNav[1].subnav[59] = new Object();
mdcHorNav[1].subnav[59].text = "Most Active Stocks";
mdcHorNav[1].subnav[59].href = "/mdc/public/page/2_3023-latetrading1-latetrading.html";
mdcHorNav[1].subnav[59].isHist = true;
mdcHorNav[1].subnav[59].indent = 0;
mdcHorNav[1].subnav[59].style = "navmenuitem";
mdcHorNav[1].subnav[60] = new Object();
mdcHorNav[1].subnav[60].text = "Biggest Gainers & Decliners";
mdcHorNav[1].subnav[60].href = "/mdc/public/page/2_3023-latetrading2-latetrading.html";
mdcHorNav[1].subnav[60].isHist = true;
mdcHorNav[1].subnav[60].indent = 0;
mdcHorNav[1].subnav[60].style = "navmenuitem";
mdcHorNav[1].subnav[61] = new Object();
mdcHorNav[1].subnav[61].text = "Closing Quote Tables";
mdcHorNav[1].subnav[61].indent = 0;
mdcHorNav[1].subnav[61].style = "navmenusec";
mdcHorNav[1].subnav[62] = new Object();
mdcHorNav[1].subnav[62].text = "NYSE MKT Stocks";
mdcHorNav[1].subnav[62].href = "/mdc/public/page/2_3024-AMEX.html";
mdcHorNav[1].subnav[62].hasCsv = true;
mdcHorNav[1].subnav[62].indent = 0;
mdcHorNav[1].subnav[62].style = "navmenuitem";

mdcHorNav[1].subnav[63] = new Object();
mdcHorNav[1].subnav[63].text = "Exchange-Traded Funds";
mdcHorNav[1].subnav[63].href = "/mdc/public/page/2_3024-USETFs.html";
mdcHorNav[1].subnav[63].hasCsv = true;
mdcHorNav[1].subnav[63].indent = 0;
mdcHorNav[1].subnav[63].style = "navmenuitem";

mdcHorNav[1].subnav[64] = new Object();
mdcHorNav[1].subnav[64].text = "Exchange-Traded Funds by Sponsor";
mdcHorNav[1].subnav[64].href = "/mdc/public/page/2_3021-usetf.html";
mdcHorNav[1].subnav[64].indent = 0;
mdcHorNav[1].subnav[64].style = "navmenuitem";

mdcHorNav[1].subnav[65] = new Object();
mdcHorNav[1].subnav[65].text = "";
mdcHorNav[1].subnav[65].href = "";
mdcHorNav[1].subnav[65].hasCsv = true;
mdcHorNav[1].subnav[65].indent = 0;
mdcHorNav[1].subnav[65].style = "navmenuitem";

mdcHorNav[1].subnav[66] = new Object();
mdcHorNav[1].subnav[66].text = "Preferred Stocks";
mdcHorNav[1].subnav[66].href = "/mdc/public/page/2_3024-Preferreds.html";
mdcHorNav[1].subnav[66].hasCsv = true;
mdcHorNav[1].subnav[66].indent = 0;
mdcHorNav[1].subnav[66].style = "navmenuitem";

mdcHorNav[1].subnav[67] = new Object();
mdcHorNav[1].subnav[67].text = "NYSE Stocks";
mdcHorNav[1].subnav[67].href = "/mdc/public/page/2_3024-NYSE.html";
mdcHorNav[1].subnav[67].hasCsv = true;
mdcHorNav[1].subnav[67].indent = 0;
mdcHorNav[1].subnav[67].style = "navmenuitem";

mdcHorNav[1].subnav[68] = new Object();
mdcHorNav[1].subnav[68].text = "Nasdaq Global Market";
mdcHorNav[1].subnav[68].href = "/mdc/public/page/2_3024-Nasdaq.html";
mdcHorNav[1].subnav[68].hasCsv = true;
mdcHorNav[1].subnav[68].indent = 0;
mdcHorNav[1].subnav[68].style = "navmenuitem";

mdcHorNav[1].subnav[69] = new Object();
mdcHorNav[1].subnav[69].text = "Nasdaq Capital Market";
mdcHorNav[1].subnav[69].href = "/mdc/public/page/2_3024-SCAP.html";
mdcHorNav[1].subnav[69].hasCsv = true;
mdcHorNav[1].subnav[69].indent = 0;
mdcHorNav[1].subnav[69].style = "navmenuitem";

mdcHorNav[1].subnav[70] = new Object();
mdcHorNav[1].subnav[70].columnBreak = true;

mdcHorNav[1].subnav[71] = new Object();
mdcHorNav[1].subnav[71].text = "IPOs and Offerings";
mdcHorNav[1].subnav[71].indent = 0;
mdcHorNav[1].subnav[71].style = "navmenusec";

mdcHorNav[1].subnav[72] = new Object();
mdcHorNav[1].subnav[72].text = "";
mdcHorNav[1].subnav[72].href = "/mdc/public/page/2_3024-ipowatch.html";
mdcHorNav[1].subnav[72].indent = 0;
mdcHorNav[1].subnav[72].style = "navmenuitem";

mdcHorNav[1].subnav[73] = new Object();
mdcHorNav[1].subnav[73].text = "";
mdcHorNav[1].subnav[73].href = "";
mdcHorNav[1].subnav[73].indent = 0;
mdcHorNav[1].subnav[73].style = "";

mdcHorNav[1].subnav[74] = new Object();
mdcHorNav[1].subnav[74].text = "";
mdcHorNav[1].subnav[74].href = "";
mdcHorNav[1].subnav[74].indent = 0;
mdcHorNav[1].subnav[74].style = "";

mdcHorNav[1].subnav[75] = new Object();
mdcHorNav[1].subnav[75].text = "IPO & Stock Offering Calendar";
mdcHorNav[1].subnav[75].href = "/mdc/public/page/2_3022-newoffer.html";
mdcHorNav[1].subnav[75].indent = 0;
mdcHorNav[1].subnav[75].style = "navmenuitem";

mdcHorNav[1].subnav[76] = new Object();
mdcHorNav[1].subnav[76].text = "Lockup Expirations";
mdcHorNav[1].subnav[76].href = "/mdc/public/page/2_3021-lockupexp.html";
mdcHorNav[1].subnav[76].indent = 0;
mdcHorNav[1].subnav[76].style = "navmenuitem";

mdcHorNav[1].subnav[77] = new Object();
mdcHorNav[1].subnav[77].text = "";
mdcHorNav[1].subnav[77].href = "";
mdcHorNav[1].subnav[77].indent = 0;
mdcHorNav[1].subnav[77].style = "";
mdcHorNav[1].subnav[78] = new Object();
mdcHorNav[1].subnav[78].text = "Shelf Registration Sales";
mdcHorNav[1].subnav[78].href = "/mdc/public/page/2_3023-offshelf.html";
mdcHorNav[1].subnav[78].indent = 0;
mdcHorNav[1].subnav[78].style = "navmenuitem";
mdcHorNav[1].subnav[79] = new Object();
mdcHorNav[1].subnav[79].text = "";
mdcHorNav[1].subnav[79].href = "";
mdcHorNav[1].subnav[79].indent = 0;
mdcHorNav[1].subnav[79].style = "";
mdcHorNav[1].subnav[80] = new Object();
mdcHorNav[1].subnav[80].text = "Options";
mdcHorNav[1].subnav[80].indent = 0;
mdcHorNav[1].subnav[80].style = "navmenusec";
mdcHorNav[1].subnav[81] = new Object();
mdcHorNav[1].subnav[81].text = "Unusual Activity: Midday";
mdcHorNav[1].subnav[81].href = "/mdc/public/page/2_3027-unusualoptmid.html";
mdcHorNav[1].subnav[81].indent = 0;
mdcHorNav[1].subnav[81].style = "navmenuitem";
mdcHorNav[1].subnav[82] = new Object();
mdcHorNav[1].subnav[82].text = "Unusual Activity: Closing";
mdcHorNav[1].subnav[82].href ="/mdc/public/page/2_3027-unusualoptclose.html";
mdcHorNav[1].subnav[82].indent = 0;
mdcHorNav[1].subnav[82].style = "navmenuitem";
mdcHorNav[1].subnav[83] = new Object();
mdcHorNav[1].subnav[83].text = "";
mdcHorNav[1].subnav[83].href = "";
mdcHorNav[1].subnav[83].indent = 0;
mdcHorNav[1].subnav[83].style = "navmenuitem";
mdcHorNav[1].subnav[84] = new Object();
mdcHorNav[1].subnav[84].text = "";
mdcHorNav[1].subnav[84].href = "";
mdcHorNav[1].subnav[84].indent = 0;
mdcHorNav[1].subnav[84].style = "navmenuitem";
mdcHorNav[1].subnav[85] = new Object();
mdcHorNav[1].subnav[85].text = "";
mdcHorNav[1].subnav[85].href = "";
mdcHorNav[1].subnav[85].indent = 0;
mdcHorNav[1].subnav[85].style = "navmenuitem";
mdcHorNav[1].subnav[86] = new Object();
mdcHorNav[1].subnav[86].text = "";
mdcHorNav[1].subnav[86].href = "";
mdcHorNav[1].subnav[86].indent = 0;
mdcHorNav[1].subnav[86].style = "navmenuitem";
mdcHorNav[1].subnav[87] = new Object();
mdcHorNav[1].subnav[87].text = "";
mdcHorNav[1].subnav[87].href = "";
mdcHorNav[1].subnav[87].indent = 0;
mdcHorNav[1].subnav[87].style = "navmenuitem";
mdcHorNav[1].subnav[88] = new Object();
mdcHorNav[1].subnav[88].text = "Weekly Snapshots";
mdcHorNav[1].subnav[88].indent = 0;
mdcHorNav[1].subnav[88].style = "navmenusec";

mdcHorNav[1].subnav[89] = new Object();
mdcHorNav[1].subnav[89].text = "ETFs";
mdcHorNav[1].subnav[89].href = "/mdc/public/page/2_3023-wklyusetf.html";
mdcHorNav[1].subnav[89].indent = 0;
mdcHorNav[1].subnav[89].style = "navmenuitem";

mdcHorNav[1].subnav[90] = new Object();
mdcHorNav[1].subnav[90].text = "Insider Trading";
mdcHorNav[1].subnav[90].href = "/mdc/public/page/2_3024-insider1.html";
mdcHorNav[1].subnav[90].indent = 0;
mdcHorNav[1].subnav[90].style = "navmenuitem";

mdcHorNav[1].subnav[91] = new Object();
mdcHorNav[1].subnav[91].text = "Patent Scorecard";
mdcHorNav[1].subnav[91].href = "/mdc/public/page/2_3022-macromkt.html";
mdcHorNav[1].subnav[91].indent = 0;
mdcHorNav[1].subnav[91].style = "navmenuitem";

mdcHorNav[1].subnav[92] = new Object();
mdcHorNav[1].subnav[92].text = "Performance by Asset Class";
mdcHorNav[1].subnav[92].href = "/public/article/hotornot.html";
mdcHorNav[1].subnav[92].indent = 0;
mdcHorNav[1].subnav[92].style = "navmenuitem";
mdcHorNav[1].subnav[92].disabled = true;

mdcHorNav[1].subnav[93] = new Object();
mdcHorNav[1].subnav[93].text = "Quarterly/Monthly Snapshots";
mdcHorNav[1].subnav[93].indent = 0;
mdcHorNav[1].subnav[93].style = "navmenusec";

mdcHorNav[1].subnav[94] = new Object();
mdcHorNav[1].subnav[94].text = "Short Interest Highlights";
mdcHorNav[1].subnav[94].href = "/mdc/public/page/2_3062-nyseshort-highlites.html";
mdcHorNav[1].subnav[94].indent = 0;
mdcHorNav[1].subnav[94].style = "navmenuitem";

mdcHorNav[1].subnav[95] = new Object();
mdcHorNav[1].subnav[95].text = "Short Interest: Stock by Stock Listing";
mdcHorNav[1].subnav[95].href = "/mdc/public/page/2_3062-shtnyse_0_9-listing.html";
mdcHorNav[1].subnav[95].indent = 0;
mdcHorNav[1].subnav[95].style = "navmenuitem";

mdcHorNav[1].subnav[96] = new Object();
mdcHorNav[1].subnav[96].text = "Monthly Global Stock Indexes";
mdcHorNav[1].subnav[96].href = "/mdc/public/page/2_3023-monthly_gblstkidx.html";
mdcHorNav[1].subnav[96].indent = 0;
mdcHorNav[1].subnav[96].style = "navmenuitem";

mdcHorNav[1].subnav[97] = new Object();
mdcHorNav[1].subnav[97].text = "Quarterly Global Stock Indexes";
mdcHorNav[1].subnav[97].href = "/mdc/public/page/2_3022-quarterly_gblstkidx.html";
mdcHorNav[1].subnav[97].indent = 0;
mdcHorNav[1].subnav[97].style = "navmenuitem";

mdcHorNav[1].subnav[98] = new Object();
mdcHorNav[1].subnav[98].text = "Quarterly Stock Review";
mdcHorNav[1].subnav[98].href = "/StockReview";
mdcHorNav[1].subnav[98].indent = 0;
mdcHorNav[1].subnav[98].style = "navmenuitem";

mdcHorNav[2] = new Object()
mdcHorNav[2].pIDs = "|2_3004|"
mdcHorNav[2].name = "International<br/>Markets"
mdcHorNav[2].href = "/mdc/public/page/mdc_international.html"
mdcHorNav[2].subnav = new Array()
mdcHorNav[2].subnav[0] = new Object();
mdcHorNav[2].subnav[0].text = "Main: Indexes, Intraday Quotes, Links to All Data";
mdcHorNav[2].subnav[0].href = "/mdc/public/page/mdc_international.html"
mdcHorNav[2].subnav[0].indent = 0;
mdcHorNav[2].subnav[0].style = "navmenupage";
mdcHorNav[2].subnav[0].changeBg = false;
mdcHorNav[2].subnav[1] = new Object();
mdcHorNav[2].subnav[1].text = "Stock Scan";
mdcHorNav[2].subnav[1].indent = 0;
mdcHorNav[2].subnav[1].style = "navmenusec";
mdcHorNav[2].subnav[2] = new Object();
mdcHorNav[2].subnav[2].text = "";
mdcHorNav[2].subnav[2].href = "";
mdcHorNav[2].subnav[2].indent = 0;
mdcHorNav[2].subnav[2].style = "navmenuitem";
mdcHorNav[2].subnav[3] = new Object();
mdcHorNav[2].subnav[3].text = "";
mdcHorNav[2].subnav[3].href = "";
mdcHorNav[2].subnav[3].indent = 0;
mdcHorNav[2].subnav[3].style = "navmenuitem";
mdcHorNav[2].subnav[4] = new Object();
mdcHorNav[2].subnav[4].text = "";
mdcHorNav[2].subnav[4].href = "";
mdcHorNav[2].subnav[4].indent = 0;
mdcHorNav[2].subnav[4].style = "navmenuitem";
mdcHorNav[2].subnav[5] = new Object();
mdcHorNav[2].subnav[5].text = "Europe's Biggest";
mdcHorNav[2].subnav[5].href = "/mdc/public/page/2_3022-scaneuro.html";
mdcHorNav[2].subnav[5].indent = 0;
mdcHorNav[2].subnav[5].style = "navmenuitem";
mdcHorNav[2].subnav[6] = new Object();
mdcHorNav[2].subnav[6].text = "";
mdcHorNav[2].subnav[6].href = "";
mdcHorNav[2].subnav[6].indent = 0;
mdcHorNav[2].subnav[6].style = "navmenuitem";
mdcHorNav[2].subnav[7] = new Object();
mdcHorNav[2].subnav[7].text = "";
mdcHorNav[2].subnav[7].indent = 0;
mdcHorNav[2].subnav[7].style = "";
mdcHorNav[2].subnav[8] = new Object();
mdcHorNav[2].subnav[8].text = "";
mdcHorNav[2].subnav[8].href = "";
mdcHorNav[2].subnav[8].indent = 0;
mdcHorNav[2].subnav[8].style = "";
mdcHorNav[2].subnav[9] = new Object();
mdcHorNav[2].subnav[9].text = "";
mdcHorNav[2].subnav[9].href = "";
mdcHorNav[2].subnav[9].indent = 0;
mdcHorNav[2].subnav[9].style = "";
mdcHorNav[2].subnav[10] = new Object();
mdcHorNav[2].subnav[10].text = "";
mdcHorNav[2].subnav[10].href = "";
mdcHorNav[2].subnav[10].indent = 0;
mdcHorNav[2].subnav[10].style = "";
mdcHorNav[2].subnav[11] = new Object();
mdcHorNav[2].subnav[11].text = "";
mdcHorNav[2].subnav[11].href = "";
mdcHorNav[2].subnav[11].indent = 0;
mdcHorNav[2].subnav[11].style = "";
mdcHorNav[2].subnav[12] = new Object();
mdcHorNav[2].subnav[12].text = "";
mdcHorNav[2].subnav[12].href = "";
mdcHorNav[2].subnav[12].indent = 0;
mdcHorNav[2].subnav[12].style = "";
mdcHorNav[2].subnav[13] = new Object();
mdcHorNav[2].subnav[13].text = "Closing Indexes";
mdcHorNav[2].subnav[13].indent = 0;
mdcHorNav[2].subnav[13].style = "navmenusec";
mdcHorNav[2].subnav[14] = new Object();
mdcHorNav[2].subnav[14].text = "Major Stock Exchange Indexes";
mdcHorNav[2].subnav[14].href = "/mdc/public/page/2_3022-intlstkidx.html";
mdcHorNav[2].subnav[14].isHist = true;
mdcHorNav[2].subnav[14].indent = 0;
mdcHorNav[2].subnav[14].style = "navmenuitem";
mdcHorNav[2].subnav[15] = new Object();
mdcHorNav[2].subnav[15].text = "";
mdcHorNav[2].subnav[15].href = "/mdc/public/page/2_3024-wsimain.html";
mdcHorNav[2].subnav[15].indent = 0;
mdcHorNav[2].subnav[15].style = "navmenuitem";
mdcHorNav[2].subnav[16] = new Object();
mdcHorNav[2].subnav[16].text = "";
mdcHorNav[2].subnav[16].href = "";
mdcHorNav[2].subnav[16].indent = 0;
mdcHorNav[2].subnav[16].style = "navmenuitem";
mdcHorNav[2].subnav[17] = new Object();
mdcHorNav[2].subnav[17].text = "Dow Jones Global TSM Sectors";
mdcHorNav[2].subnav[17].href = "/mdc/public/page/2_3022-sectortitan.html";
mdcHorNav[2].subnav[17].indent = 0;
mdcHorNav[2].subnav[17].style = "navmenuitem";
mdcHorNav[2].subnav[18] = new Object();
mdcHorNav[2].subnav[18].text = "";
mdcHorNav[2].subnav[18].href = "";
mdcHorNav[2].subnav[18].indent = 0;
mdcHorNav[2].subnav[18].style = "";
mdcHorNav[2].subnav[19] = new Object();
mdcHorNav[2].subnav[19].text = "Funds";
mdcHorNav[2].subnav[19].indent = 0;
mdcHorNav[2].subnav[19].style = "navmenusec";
mdcHorNav[2].subnav[20] = new Object();
mdcHorNav[2].subnav[20].text = "Europe Exchange Traded Funds";
mdcHorNav[2].subnav[20].href = "/mdc/public/page/2_3024-EuropeanETFs.html";
mdcHorNav[2].subnav[20].indent = 0;
mdcHorNav[2].subnav[20].style = "navmenuitem";
mdcHorNav[2].subnav[21] = new Object();
mdcHorNav[2].subnav[21].text = "International Investment Funds";
mdcHorNav[2].subnav[21].href = "/mdc/public/npage/MS_intl_mutual_funds_quickrank.html";
mdcHorNav[2].subnav[21].indent = 0;
mdcHorNav[2].subnav[21].style = "navmenuitem";
mdcHorNav[2].subnav[22] = new Object();
mdcHorNav[2].subnav[22].text = "International Credit Markets";
mdcHorNav[2].subnav[22].indent = 0;
mdcHorNav[2].subnav[22].style = "navmenusec";
mdcHorNav[2].subnav[23] = new Object();
mdcHorNav[2].subnav[23].text = "Global Government Bonds";
mdcHorNav[2].subnav[23].href = "/mdc/public/page/2_3022-govtbonds.html";
mdcHorNav[2].subnav[23].isHist = true;
mdcHorNav[2].subnav[23].indent = 0;
mdcHorNav[2].subnav[23].style = "navmenuitem";
mdcHorNav[2].subnav[24] = new Object();
mdcHorNav[2].subnav[24].text = "Quarterly/Monthly Snapshots";
mdcHorNav[2].subnav[24].indent = 0;
mdcHorNav[2].subnav[24].style = "navmenusec";
mdcHorNav[2].subnav[25] = new Object();
mdcHorNav[2].subnav[25].text = "Monthly Global Stock Indexes ";
mdcHorNav[2].subnav[25].href = "/mdc/public/page/2_3023-monthly_gblstkidx.html";
mdcHorNav[2].subnav[25].indent = 0;
mdcHorNav[2].subnav[25].style = "navmenuitem";

mdcHorNav[2].subnav[26] = new Object();
mdcHorNav[2].subnav[26].text = "Quarterly Global Stock Indexes ";
mdcHorNav[2].subnav[26].href = "/mdc/public/page/2_3022-quarterly_gblstkidx.html";
mdcHorNav[2].subnav[26].indent = 0;
mdcHorNav[2].subnav[26].style = "navmenuitem";

mdcHorNav[2].subnav[27] = new Object();
mdcHorNav[2].subnav[27].columnBreak = true;
mdcHorNav[2].subnav[28] = new Object();
mdcHorNav[2].subnav[28].text = "Asia: Closing Prices";
mdcHorNav[2].subnav[28].indent = 0;
mdcHorNav[2].subnav[28].style = "navmenusec";
mdcHorNav[2].subnav[29] = new Object();
mdcHorNav[2].subnav[29].text = "Australia";
mdcHorNav[2].subnav[29].href = "/mdc/public/page/2_3024-AsianStocks_AUSTRALIA.html";
mdcHorNav[2].subnav[29].indent = 0;
mdcHorNav[2].subnav[29].style = "navmenuitem";
mdcHorNav[2].subnav[30] = new Object();
mdcHorNav[2].subnav[30].text = "Most Actives";
mdcHorNav[2].subnav[30].href = "/mdc/public/page/2_3024-ma_sydney.html";
mdcHorNav[2].subnav[30].indent = 1;
mdcHorNav[2].subnav[30].style = "navmenuitem";
mdcHorNav[2].subnav[31] = new Object();
mdcHorNav[2].subnav[31].text = "China - Shanghai";
mdcHorNav[2].subnav[31].href = "/mdc/public/page/2_3024-AsianStocks_SHANGHAI_B.html";
mdcHorNav[2].subnav[31].indent = 0;
mdcHorNav[2].subnav[31].style = "navmenuitem";
mdcHorNav[2].subnav[32] = new Object();
mdcHorNav[2].subnav[32].text = "China - Shenzhen";
mdcHorNav[2].subnav[32].href = "/mdc/public/page/2_3024-AsianStocks_SHENZHEN_B.html";
mdcHorNav[2].subnav[32].indent = 0;
mdcHorNav[2].subnav[32].style = "navmenuitem";
mdcHorNav[2].subnav[33] = new Object();
mdcHorNav[2].subnav[33].text = "Hong Kong";
mdcHorNav[2].subnav[33].href = "/mdc/public/page/2_3024-AsianStocks_HONG_KONG.html";
mdcHorNav[2].subnav[33].indent = 0;
mdcHorNav[2].subnav[33].style = "navmenuitem";
mdcHorNav[2].subnav[34] = new Object();
mdcHorNav[2].subnav[34].text = "Most Actives";
mdcHorNav[2].subnav[34].href = "/mdc/public/page/2_3024-ma_hongkong.html";
mdcHorNav[2].subnav[34].indent = 1;
mdcHorNav[2].subnav[34].style = "navmenuitem";
mdcHorNav[2].subnav[35] = new Object();
mdcHorNav[2].subnav[35].text = "India";
mdcHorNav[2].subnav[35].href = "/mdc/public/page/2_3024-AsianStocks_MUMBAI.html";
mdcHorNav[2].subnav[35].indent = 0;
mdcHorNav[2].subnav[35].style = "navmenuitem";
mdcHorNav[2].subnav[36] = new Object();
mdcHorNav[2].subnav[36].text = "Indonesia";
mdcHorNav[2].subnav[36].href = "/mdc/public/page/2_3024-AsianStocks_JAKARTA.html";
mdcHorNav[2].subnav[36].indent = 0;
mdcHorNav[2].subnav[36].style = "navmenuitem";
mdcHorNav[2].subnav[37] = new Object();
mdcHorNav[2].subnav[37].text = "Japan";
mdcHorNav[2].subnav[37].href = "/mdc/public/page/2_3024-AsianStocks_TOKYO.html";
mdcHorNav[2].subnav[37].indent = 0;
mdcHorNav[2].subnav[37].style = "navmenuitem";
mdcHorNav[2].subnav[38] = new Object();
mdcHorNav[2].subnav[38].text = "Most Actives";
mdcHorNav[2].subnav[38].href = "/mdc/public/page/2_3024-ma_tokyo.html";
mdcHorNav[2].subnav[38].indent = 1;
mdcHorNav[2].subnav[38].style = "navmenuitem";
mdcHorNav[2].subnav[39] = new Object();
mdcHorNav[2].subnav[39].text = "Malaysia";
mdcHorNav[2].subnav[39].href = "/mdc/public/page/2_3024-AsianStocks_KUALA_LUMPUR.html";
mdcHorNav[2].subnav[39].indent = 0;
mdcHorNav[2].subnav[39].style = "navmenuitem";
mdcHorNav[2].subnav[40] = new Object();
mdcHorNav[2].subnav[40].text = "Most Actives";
mdcHorNav[2].subnav[40].href = "/mdc/public/page/2_3024-ma_kualalumpur.html";
mdcHorNav[2].subnav[40].indent = 1;
mdcHorNav[2].subnav[40].style = "navmenuitem";
mdcHorNav[2].subnav[41] = new Object();
mdcHorNav[2].subnav[41].text = "New Zealand";
mdcHorNav[2].subnav[41].href = "/mdc/public/page/2_3024-AsianStocks_WELLINGTON.html";
mdcHorNav[2].subnav[41].indent = 0;
mdcHorNav[2].subnav[41].style = "navmenuitem";

mdcHorNav[2].subnav[42] = new Object();
mdcHorNav[2].subnav[42].text = "Pakistan";
mdcHorNav[2].subnav[42].href = "/mdc/public/page/2_3024-cl_pakis.html";
mdcHorNav[2].subnav[42].indent = 0;
mdcHorNav[2].subnav[42].style = "navmenuitem";
mdcHorNav[2].subnav[42].disabled = true;

mdcHorNav[2].subnav[43] = new Object();
mdcHorNav[2].subnav[43].text = "Philippines";
mdcHorNav[2].subnav[43].href = "/mdc/public/page/2_3024-AsianStocks_MANILA.html";
mdcHorNav[2].subnav[43].indent = 0;
mdcHorNav[2].subnav[43].style = "navmenuitem";
mdcHorNav[2].subnav[44] = new Object();
mdcHorNav[2].subnav[44].text = "Singapore";
mdcHorNav[2].subnav[44].href = "/mdc/public/page/2_3024-AsianStocks_SINGAPORE.html";
mdcHorNav[2].subnav[44].indent = 0;
mdcHorNav[2].subnav[44].style = "navmenuitem";
mdcHorNav[2].subnav[45] = new Object();
mdcHorNav[2].subnav[45].text = "Most Actives";
mdcHorNav[2].subnav[45].href = "/mdc/public/page/2_3024-ma_singapore.html";
mdcHorNav[2].subnav[45].indent = 1;
mdcHorNav[2].subnav[45].style = "navmenuitem";
mdcHorNav[2].subnav[46] = new Object();
mdcHorNav[2].subnav[46].text = "South Korea";
mdcHorNav[2].subnav[46].href = "/mdc/public/page/2_3024-AsianStocks_SEOUL.html";
mdcHorNav[2].subnav[46].indent = 0;
mdcHorNav[2].subnav[46].style = "navmenuitem";

mdcHorNav[2].subnav[47] = new Object();
mdcHorNav[2].subnav[47].text = "Sri Lanka";
mdcHorNav[2].subnav[47].href = "/mdc/public/page/2_3024-cl_srila.html";
mdcHorNav[2].subnav[47].indent = 0;
mdcHorNav[2].subnav[47].style = "navmenuitem";
mdcHorNav[2].subnav[47].disabled = true;

mdcHorNav[2].subnav[48] = new Object();
mdcHorNav[2].subnav[48].text = "Taiwan";
mdcHorNav[2].subnav[48].href = "/mdc/public/page/2_3024-AsianStocks_TAIPEI.html";
mdcHorNav[2].subnav[48].indent = 0;
mdcHorNav[2].subnav[48].style = "navmenuitem";
mdcHorNav[2].subnav[49] = new Object();
mdcHorNav[2].subnav[49].text = "Thailand";
mdcHorNav[2].subnav[49].href = "/mdc/public/page/2_3024-AsianStocks_BANGKOK.html";
mdcHorNav[2].subnav[49].indent = 0;
mdcHorNav[2].subnav[49].style = "navmenuitem";
mdcHorNav[2].subnav[50] = new Object();
mdcHorNav[2].subnav[50].text = "Americas: Closing Prices";
mdcHorNav[2].subnav[50].indent = 0;
mdcHorNav[2].subnav[50].style = "navmenusec";
mdcHorNav[2].subnav[51] = new Object();
//mdcHorNav[2].subnav[48].text = "Argentina";
//mdcHorNav[2].subnav[48].href = "/mdc/public/page/2_3024-cl_argen.html";
mdcHorNav[2].subnav[51].text = "";
mdcHorNav[2].subnav[51].href = "";
mdcHorNav[2].subnav[51].indent = 0;
mdcHorNav[2].subnav[51].style = "navmenuitem";
mdcHorNav[2].subnav[52] = new Object();
mdcHorNav[2].subnav[52].text = "Brazil";
mdcHorNav[2].subnav[52].href = "/mdc/public/page/2_3024-cl_brazi.html";
mdcHorNav[2].subnav[52].indent = 0;
mdcHorNav[2].subnav[52].style = "navmenuitem";
mdcHorNav[2].subnav[53] = new Object();
mdcHorNav[2].subnav[53].text = "Most Actives";
mdcHorNav[2].subnav[53].href = "/mdc/public/page/2_3024-ma_saopaulo.html";
mdcHorNav[2].subnav[53].indent = 1;
mdcHorNav[2].subnav[53].style = "navmenuitem";
mdcHorNav[2].subnav[54] = new Object();
mdcHorNav[2].subnav[54].text = "Canada";
mdcHorNav[2].subnav[54].href = "/mdc/public/page/2_3024-Toronto.html";
mdcHorNav[2].subnav[54].indent = 0;
mdcHorNav[2].subnav[54].style = "navmenuitem";
mdcHorNav[2].subnav[55] = new Object();
mdcHorNav[2].subnav[55].text = "Chile";
mdcHorNav[2].subnav[55].href = "/mdc/public/page/2_3024-cl_chile.html";
mdcHorNav[2].subnav[55].indent = 0;
mdcHorNav[2].subnav[55].style = "navmenuitem";
mdcHorNav[2].subnav[56] = new Object();
mdcHorNav[2].subnav[56].text = "Mexico";
mdcHorNav[2].subnav[56].href = "/mdc/public/page/2_3024-cl_mexic.html";
mdcHorNav[2].subnav[56].indent = 0;
mdcHorNav[2].subnav[56].style = "navmenuitem";
mdcHorNav[2].subnav[57] = new Object();
mdcHorNav[2].subnav[57].text = "Most Actives";
mdcHorNav[2].subnav[57].href = "/mdc/public/page/2_3024-ma_mexicocity.html";
mdcHorNav[2].subnav[57].indent = 1;
mdcHorNav[2].subnav[57].style = "navmenuitem";
mdcHorNav[2].subnav[58] = new Object();
mdcHorNav[2].subnav[58].text = "";
mdcHorNav[2].subnav[58].href = "";
mdcHorNav[2].subnav[58].indent = 0;
mdcHorNav[2].subnav[58].style = "navmenuitem";


mdcHorNav[2].subnav[59] = new Object();
mdcHorNav[2].subnav[59].text = "Other Markets: Closing Prices";
mdcHorNav[2].subnav[59].indent = 0;
mdcHorNav[2].subnav[59].style = "navmenusec";

mdcHorNav[2].subnav[60] = new Object();
mdcHorNav[2].subnav[60].text = "Israel";
mdcHorNav[2].subnav[60].href = "/mdc/public/page/2_3024-EuropeanStocks_Tel_Aviv.html";
mdcHorNav[2].subnav[60].indent = 0;
mdcHorNav[2].subnav[60].style = "navmenuitem";


mdcHorNav[2].subnav[61] = new Object();
mdcHorNav[2].subnav[61].text = "South Africa";
mdcHorNav[2].subnav[61].href = "/mdc/public/page/2_3024-EuropeanStocks_Johannesburg.html";
mdcHorNav[2].subnav[61].indent = 0;
mdcHorNav[2].subnav[61].style = "navmenuitem";

mdcHorNav[2].subnav[62] = new Object();
mdcHorNav[2].subnav[62].columnBreak = true;


mdcHorNav[2].subnav[63] = new Object();
mdcHorNav[2].subnav[63].text = "Europe: Closing Prices";
mdcHorNav[2].subnav[63].indent = 0;
mdcHorNav[2].subnav[63].style = "navmenusec";

mdcHorNav[2].subnav[64] = new Object();
mdcHorNav[2].subnav[64].text = "Austria";
mdcHorNav[2].subnav[64].href = "/mdc/public/page/2_3024-EuropeanStocks_Vienna.html";
mdcHorNav[2].subnav[64].indent = 0;
mdcHorNav[2].subnav[64].style = "navmenuitem";
mdcHorNav[2].subnav[65] = new Object();
mdcHorNav[2].subnav[65].text = "Belgium";
mdcHorNav[2].subnav[65].href = "/mdc/public/page/2_3024-EuropeanStocks_Brussels.html";
mdcHorNav[2].subnav[65].indent = 0;
mdcHorNav[2].subnav[65].style = "navmenuitem";


mdcHorNav[2].subnav[66] = new Object();
mdcHorNav[2].subnav[66].text = "Britain";
mdcHorNav[2].subnav[66].href = "/mdc/public/page/2_3024-EuropeanStocks_London.html";
mdcHorNav[2].subnav[66].indent = 0;
mdcHorNav[2].subnav[66].style = "navmenuitem";

mdcHorNav[2].subnav[67] = new Object();
mdcHorNav[2].subnav[67].text = "Most Actives";
mdcHorNav[2].subnav[67].href = "/mdc/public/page/2_3024-ma_london.html";
mdcHorNav[2].subnav[67].indent = 1;
mdcHorNav[2].subnav[67].style = "navmenuitem";

mdcHorNav[2].subnav[68] = new Object();
mdcHorNav[2].subnav[68].text = "Czech Republic";
mdcHorNav[2].subnav[68].href = "/mdc/public/page/2_3024-EuropeanStocks_Prague.html";
mdcHorNav[2].subnav[68].indent = 0;
mdcHorNav[2].subnav[68].style = "navmenuitem";

mdcHorNav[2].subnav[69] = new Object();
mdcHorNav[2].subnav[69].text = "Denmark";
mdcHorNav[2].subnav[69].href = "/mdc/public/page/2_3024-EuropeanStocks_Copenhagen.html";
mdcHorNav[2].subnav[69].indent = 0;
mdcHorNav[2].subnav[69].style = "navmenuitem";
mdcHorNav[2].subnav[70] = new Object();
mdcHorNav[2].subnav[70].text = "Finland";
mdcHorNav[2].subnav[70].href = "/mdc/public/page/2_3024-EuropeanStocks_Helsinki.html";
mdcHorNav[2].subnav[70].indent = 0;
mdcHorNav[2].subnav[70].style = "navmenuitem";
mdcHorNav[2].subnav[71] = new Object();
mdcHorNav[2].subnav[71].text = "France";
mdcHorNav[2].subnav[71].href = "/mdc/public/page/2_3024-EuropeanStocks_Paris.html";
mdcHorNav[2].subnav[71].indent = 0;
mdcHorNav[2].subnav[71].style = "navmenuitem";

mdcHorNav[2].subnav[72] = new Object();
mdcHorNav[2].subnav[72].text = "Most Actives";
mdcHorNav[2].subnav[72].href = "/mdc/public/page/2_3024-ma_paris.html";
mdcHorNav[2].subnav[72].indent = 1;
mdcHorNav[2].subnav[72].style = "navmenuitem";

mdcHorNav[2].subnav[73] = new Object();
mdcHorNav[2].subnav[73].text = "Germany";
mdcHorNav[2].subnav[73].href = "/mdc/public/page/2_3024-EuropeanStocks_Frankfurt.html";
mdcHorNav[2].subnav[73].indent = 0;
mdcHorNav[2].subnav[73].style = "navmenuitem";

mdcHorNav[2].subnav[74] = new Object();
mdcHorNav[2].subnav[74].text = "Most Actives";
mdcHorNav[2].subnav[74].href = "/mdc/public/page/2_3024-ma_frankfurt.html";
mdcHorNav[2].subnav[74].indent = 1;
mdcHorNav[2].subnav[74].style = "navmenuitem";

mdcHorNav[2].subnav[75] = new Object();
mdcHorNav[2].subnav[75].text = "Greece";
mdcHorNav[2].subnav[75].href = "/mdc/public/page/2_3024-EuropeanStocks_Athens.html";
mdcHorNav[2].subnav[75].indent = 0;
mdcHorNav[2].subnav[75].style = "navmenuitem";


mdcHorNav[2].subnav[76] = new Object();
mdcHorNav[2].subnav[76].text = "Hungary";
mdcHorNav[2].subnav[76].href = "/mdc/public/page/2_3024-EuropeanStocks_Budapest.html";
mdcHorNav[2].subnav[76].indent = 0;
mdcHorNav[2].subnav[76].style = "navmenuitem";


mdcHorNav[2].subnav[77] = new Object();
mdcHorNav[2].subnav[77].text = "Italy";
mdcHorNav[2].subnav[77].href = "/mdc/public/page/2_3024-EuropeanStocks_Milan.html";
mdcHorNav[2].subnav[77].indent = 0;
mdcHorNav[2].subnav[77].style = "navmenuitem";
mdcHorNav[2].subnav[78] = new Object();
mdcHorNav[2].subnav[78].text = "Most Actives";
mdcHorNav[2].subnav[78].href = "/mdc/public/page/2_3024-ma_milan.html";
mdcHorNav[2].subnav[78].indent = 1;
mdcHorNav[2].subnav[78].style = "navmenuitem";

mdcHorNav[2].subnav[79] = new Object();
mdcHorNav[2].subnav[79].text = "Ireland";
mdcHorNav[2].subnav[79].href = "/mdc/public/page/2_3024-EuropeanStocks_Dublin.html";
mdcHorNav[2].subnav[79].indent = 0;
mdcHorNav[2].subnav[79].style = "navmenuitem";
mdcHorNav[2].subnav[80] = new Object();
mdcHorNav[2].subnav[80].text = "Netherlands";
mdcHorNav[2].subnav[80].href = "/mdc/public/page/2_3024-EuropeanStocks_Amsterdam.html";
mdcHorNav[2].subnav[80].indent = 0;
mdcHorNav[2].subnav[80].style = "navmenuitem";

mdcHorNav[2].subnav[81] = new Object();
mdcHorNav[2].subnav[81].text = "Most Actives";
mdcHorNav[2].subnav[81].href = "/mdc/public/page/2_3024-ma_amsterdam.html";
mdcHorNav[2].subnav[81].indent = 1;
mdcHorNav[2].subnav[81].style = "navmenuitem";

mdcHorNav[2].subnav[82] = new Object();
mdcHorNav[2].subnav[82].text = "Norway";
mdcHorNav[2].subnav[82].href = "/mdc/public/page/2_3024-EuropeanStocks_Oslo.html";
mdcHorNav[2].subnav[82].indent = 0;
mdcHorNav[2].subnav[82].style = "navmenuitem";

mdcHorNav[2].subnav[83] = new Object();
mdcHorNav[2].subnav[83].text = "Poland";
mdcHorNav[2].subnav[83].href = "/mdc/public/page/2_3024-EuropeanStocks_Warsaw.html";
mdcHorNav[2].subnav[83].indent = 0;
mdcHorNav[2].subnav[83].style = "navmenuitem";

mdcHorNav[2].subnav[84] = new Object();
mdcHorNav[2].subnav[84].text = "Portugal";
mdcHorNav[2].subnav[84].href = "/mdc/public/page/2_3024-EuropeanStocks_Lisbon.html";
mdcHorNav[2].subnav[84].indent = 0;
mdcHorNav[2].subnav[84].style = "navmenuitem";

mdcHorNav[2].subnav[85] = new Object();
mdcHorNav[2].subnav[85].text = "Russia";
mdcHorNav[2].subnav[85].href = "/mdc/public/page/2_3024-EuropeanStocks_Moscow.html";
mdcHorNav[2].subnav[85].indent = 0;
mdcHorNav[2].subnav[85].style = "navmenuitem";



mdcHorNav[2].subnav[86] = new Object();
mdcHorNav[2].subnav[86].text = "Spain";
mdcHorNav[2].subnav[86].href = "/mdc/public/page/2_3024-EuropeanStocks_Madrid.html";
mdcHorNav[2].subnav[86].indent = 0;
mdcHorNav[2].subnav[86].style = "navmenuitem";
mdcHorNav[2].subnav[87] = new Object();
mdcHorNav[2].subnav[87].text = "Most Actives";
mdcHorNav[2].subnav[87].href = "/mdc/public/page/2_3024-ma_madrid.html";
mdcHorNav[2].subnav[87].indent = 1;
mdcHorNav[2].subnav[87].style = "navmenuitem";
mdcHorNav[2].subnav[88] = new Object();
mdcHorNav[2].subnav[88].text = "Sweden";
mdcHorNav[2].subnav[88].href = "/mdc/public/page/2_3024-EuropeanStocks_Stockholm.html";
mdcHorNav[2].subnav[88].indent = 0;
mdcHorNav[2].subnav[88].style = "navmenuitem";

mdcHorNav[2].subnav[89] = new Object();
mdcHorNav[2].subnav[89].text = "Switzerland";
mdcHorNav[2].subnav[89].href = "/mdc/public/page/2_3024-EuropeanStocks_Zurich.html";
mdcHorNav[2].subnav[89].indent = 0;
mdcHorNav[2].subnav[89].style = "navmenuitem";

mdcHorNav[2].subnav[90] = new Object();
mdcHorNav[2].subnav[90].text = "Most Actives";
mdcHorNav[2].subnav[90].href = "/mdc/public/page/2_3024-ma_zurich.html";
mdcHorNav[2].subnav[90].indent = 1;
mdcHorNav[2].subnav[90].style = "navmenuitem";

mdcHorNav[2].subnav[91] = new Object();
mdcHorNav[2].subnav[91].text = "Turkey";
mdcHorNav[2].subnav[91].href = "/mdc/public/page/2_3024-EuropeanStocks_Istanbul.html";
mdcHorNav[2].subnav[91].indent = 0;
mdcHorNav[2].subnav[91].style = "navmenuitem";

mdcHorNav[3] = new Object()
mdcHorNav[3].pIDs = "|2_3006|"
mdcHorNav[3].name = "ETFs"
mdcHorNav[3].href = "/redirect/etfresearch.html"
mdcHorNav[3].subnav = new Array()
mdcHorNav[3].subnav[0] = new Object();
mdcHorNav[3].subnav[0].text = "Main: Intraday Quotes, Research, Screener";
mdcHorNav[3].subnav[0].href = "/redirect/etfresearch.html";
mdcHorNav[3].subnav[0].indent = 0;
mdcHorNav[3].subnav[0].style = "navmenupage";
mdcHorNav[3].subnav[0].changeBg = false;
mdcHorNav[3].subnav[1] = new Object();
mdcHorNav[3].subnav[1].text = "Most Actives, Gainers and Decliners";
mdcHorNav[3].subnav[1].href = "/mdc/public/page/2_3052.html";
mdcHorNav[3].subnav[1].indent = 0;
mdcHorNav[3].subnav[1].style = "navmenuitem";
mdcHorNav[3].subnav[2] = new Object();
mdcHorNav[3].subnav[2].text = "Sort ETFs by Investment Objective";
mdcHorNav[3].subnav[2].href = "/public/quotes/browse_etfs.html";
mdcHorNav[3].subnav[2].indent = 0;
mdcHorNav[3].subnav[2].style = "navmenuitem";
mdcHorNav[3].subnav[3] = new Object();
mdcHorNav[3].subnav[3].text = "Screen ETFs Using 14 Criteria";
mdcHorNav[3].subnav[3].href = "/public/quotes/etf_screener.html";
mdcHorNav[3].subnav[3].indent = 0;
mdcHorNav[3].subnav[3].style = "navmenuitem";
mdcHorNav[3].subnav[4] = new Object();
mdcHorNav[3].subnav[4].text = "Closing Prices of ETFs";
mdcHorNav[3].subnav[4].href = "/mdc/public/page/2_3024-USETFs.html";
mdcHorNav[3].subnav[4].hasCsv = true;
mdcHorNav[3].subnav[4].indent = 0;
mdcHorNav[3].subnav[4].style = "navmenuitem";
mdcHorNav[3].subnav[5] = new Object();
mdcHorNav[3].subnav[5].text = "Closing Prices of ETFs by Sponsor";
mdcHorNav[3].subnav[5].href = "/mdc/public/page/2_3021-usetf.html";
mdcHorNav[3].subnav[5].indent = 0;
mdcHorNav[3].subnav[5].style = "navmenuitem";
mdcHorNav[3].subnav[6] = new Object();
mdcHorNav[3].subnav[6].text = "Closing Prices of ETFs: Weekly Snapshot";
mdcHorNav[3].subnav[6].href = "/mdc/public/page/2_3023-wklyusetf.html";
mdcHorNav[3].subnav[6].indent = 0;
mdcHorNav[3].subnav[6].style = "navmenuitem";
mdcHorNav[3].subnav[7] = new Object();
mdcHorNav[3].subnav[7].text = "Closing Prices of ETFs: Europe";
mdcHorNav[3].subnav[7].href = "/mdc/public/page/2_3024-EuropeanETFs.html";
mdcHorNav[3].subnav[7].indent = 0;
mdcHorNav[3].subnav[7].style = "navmenuitem";

mdcHorNav[4] = new Object()
mdcHorNav[4].pIDs = "|2_3008|"
mdcHorNav[4].name = "Mutual Funds"
mdcHorNav[4].href = "/redirect/mutualfundresearch.html"
mdcHorNav[4].subnav = new Array()
mdcHorNav[4].subnav[0] = new Object();
mdcHorNav[4].subnav[0].text = "Main: Quotes, Research, Links to All Data";
mdcHorNav[4].subnav[0].indent = 0;
mdcHorNav[4].subnav[0].style = "navmenupage";
mdcHorNav[4].subnav[0].changeBg = false;

mdcHorNav[4].subnav[1] = new Object();
mdcHorNav[4].subnav[1].text = "Mutual Fund Main";
mdcHorNav[4].subnav[1].href = "/redirect/mutualfundresearch.html";
mdcHorNav[4].subnav[1].indent = 0;
mdcHorNav[4].subnav[1].style = "navmenusec";


mdcHorNav[4].subnav[2] = new Object();
mdcHorNav[4].subnav[2].text = "Asia Fund Research";
mdcHorNav[4].subnav[2].href = "/public/page/mutual-funds-quickrank-asia.html";
mdcHorNav[4].subnav[2].indent = 0;
mdcHorNav[4].subnav[2].style = "navmenuitem";

mdcHorNav[4].subnav[3] = new Object();
mdcHorNav[4].subnav[3].text = "Europe Fund Research";
mdcHorNav[4].subnav[3].href = "/public/page/mutual-funds-quickrank-europe.html";
mdcHorNav[4].subnav[3].indent = 0;
mdcHorNav[4].subnav[3].style = "navmenuitem";

mdcHorNav[4].subnav[4] = new Object();
mdcHorNav[4].subnav[4].text = "Asia Fund Screener";
mdcHorNav[4].subnav[4].href = "/public/page/fund_screener_asia_full.html";
mdcHorNav[4].subnav[4].indent = 0;
mdcHorNav[4].subnav[4].style = "navmenuitem";

mdcHorNav[4].subnav[5] = new Object();
mdcHorNav[4].subnav[5].text = "Europe Fund Screener";
mdcHorNav[4].subnav[5].href = "/public/page/fund_screener_europe_full.html";
mdcHorNav[4].subnav[5].indent = 0;
mdcHorNav[4].subnav[5].style = "navmenuitem";

mdcHorNav[4].subnav[6] = new Object();
mdcHorNav[4].subnav[6].text = "Asia Fund Compare";
mdcHorNav[4].subnav[6].href = "/public/page/mutual_fund_compare_asia.html";
mdcHorNav[4].subnav[6].indent = 0;
mdcHorNav[4].subnav[6].style = "navmenuitem"; 

mdcHorNav[4].subnav[7] = new Object();
mdcHorNav[4].subnav[7].text = "Europe Fund Compare";
mdcHorNav[4].subnav[7].href = "/public/page/mutual_fund_compare_europe.html";
mdcHorNav[4].subnav[7].indent = 0;
mdcHorNav[4].subnav[7].style = "navmenuitem"; 

mdcHorNav[4].subnav[8] = new Object();
mdcHorNav[4].subnav[8].text = "Global Hedge Fund Data";
mdcHorNav[4].subnav[8].href = "/public/page/hedgefund_quickrank.html";
mdcHorNav[4].subnav[8].indent = 0;
mdcHorNav[4].subnav[8].style = "navmenuitem";

mdcHorNav[4].subnav[9] = new Object();
mdcHorNav[4].subnav[9].text = "Global Hedge Fund Compare";
mdcHorNav[4].subnav[9].href = "/public/page/hedge_fund_compare_intl.html";
mdcHorNav[4].subnav[9].indent = 0;
mdcHorNav[4].subnav[9].style = "navmenuitem";

mdcHorNav[4].subnav[10] = new Object();
mdcHorNav[4].subnav[10].text = "US Funds Data";
mdcHorNav[4].subnav[10].indent = 0;
mdcHorNav[4].subnav[10].style = "navmenusec";

mdcHorNav[4].subnav[11] = new Object();
mdcHorNav[4].subnav[11].text = "Fund Families: Research and Performance"
mdcHorNav[4].subnav[11].href = "/public/fund/page/fund_family_alpha.html";
mdcHorNav[4].subnav[11].indent = 0;
mdcHorNav[4].subnav[11].style = "navmenuitem";

mdcHorNav[4].subnav[12] = new Object();
mdcHorNav[4].subnav[12].text = "Fund Screener";
mdcHorNav[4].subnav[12].href = "/public/quotes/mutualfund_screener.html";
mdcHorNav[4].subnav[12].indent = 0;
mdcHorNav[4].subnav[12].style = "navmenuitem";

mdcHorNav[4].subnav[13] = new Object();
mdcHorNav[4].subnav[13].text = "Fund Yardsticks";
mdcHorNav[4].subnav[13].href = "/mdc/public/page/2_3023-fundyrdstick.html";
mdcHorNav[4].subnav[13].indent = 0;
mdcHorNav[4].subnav[13].style = "navmenuitem";


mdcHorNav[4].subnav[14] = new Object();
mdcHorNav[4].subnav[14].text = "Lipper Indexes";
mdcHorNav[4].subnav[14].href = "/mdc/public/page/2_3020-lipperindx.html";
mdcHorNav[4].subnav[14].indent = 0;
mdcHorNav[4].subnav[14].style = "navmenuitem";

mdcHorNav[4].subnav[15] = new Object();
mdcHorNav[4].subnav[15].text = "Scorecards: Rankings by Category";
mdcHorNav[4].subnav[15].href = "/public/fund/page/fund_scorecards.html";
mdcHorNav[4].subnav[15].indent = 0;
mdcHorNav[4].subnav[15].style = "navmenuitem";

mdcHorNav[4].subnav[16] = new Object();
mdcHorNav[4].subnav[16].text = "Daily Price Tables";
mdcHorNav[4].subnav[16].indent = 0;
mdcHorNav[4].subnav[16].style = "navmenusec";

mdcHorNav[4].subnav[17] = new Object();
mdcHorNav[4].subnav[17].text = "Closed-End Funds by Category";
mdcHorNav[4].subnav[17].href = "/mdc/public/page/2_3040-CEFmain.html";
mdcHorNav[4].subnav[17].indent = 0;
mdcHorNav[4].subnav[17].style = "navmenuitem";

mdcHorNav[4].subnav[18] = new Object();
mdcHorNav[4].subnav[18].text = "Closed-End Funds: Closing Table";
mdcHorNav[4].subnav[18].href = "/mdc/public/page/2_3024-CEF.html";
mdcHorNav[4].subnav[18].hasCsv = true;
mdcHorNav[4].subnav[18].indent = 0;
mdcHorNav[4].subnav[18].style = "navmenuitem";

mdcHorNav[4].subnav[19] = new Object();
mdcHorNav[4].subnav[19].text = "Closing Prices of Mutual Funds";
mdcHorNav[4].subnav[19].href = "/mdc/public/page/2_3048-usmfunds_A-usmfunds.html";
mdcHorNav[4].subnav[19].indent = 0;
mdcHorNav[4].subnav[19].style = "navmenuitem";

mdcHorNav[4].subnav[20] = new Object();
mdcHorNav[4].subnav[20].text = "International Investment Funds";
mdcHorNav[4].subnav[20].href = "/mdc/public/page/MS_intl_mutual_funds_quickrank.html";
mdcHorNav[4].subnav[20].indent = 0;
mdcHorNav[4].subnav[20].style = "navmenuitem";

mdcHorNav[4].subnav[21] = new Object();
mdcHorNav[4].subnav[21].text = "Money Market Funds";
mdcHorNav[4].subnav[21].href = "/mdc/public/page/2_3020-moneymktfund.html";
mdcHorNav[4].subnav[21].indent = 0;
mdcHorNav[4].subnav[21].style = "navmenuitem";

mdcHorNav[4].subnav[22] = new Object();
mdcHorNav[4].subnav[22].text = "Variable Annuities";
mdcHorNav[4].subnav[22].href = "/mdc/public/page/2_3029-Ann_1_Aa_Al-Ann_1_0_0-1.html";
mdcHorNav[4].subnav[22].indent = 0;
mdcHorNav[4].subnav[22].style = "navmenuitem";

mdcHorNav[4].subnav[23] = new Object();
mdcHorNav[4].subnav[23].text = "Monthly & Quarterly Reviews";
mdcHorNav[4].subnav[23].indent = 0;
mdcHorNav[4].subnav[23].style = "navmenusec";

mdcHorNav[4].subnav[24] = new Object();
mdcHorNav[4].subnav[24].text = "Funds Analysis Report";
mdcHorNav[4].subnav[24].href = "http://wsj.com/FundsAnalysis";
mdcHorNav[4].subnav[24].indent = 0;
mdcHorNav[4].subnav[24].style = "navmenuitem";

mdcHorNav[5] = new Object()
mdcHorNav[5].pIDs = "|2_3010|"
mdcHorNav[5].name = "Bonds, Rates &<br/>Credit Markets"
mdcHorNav[5].href = "/mdc/public/page/mdc_bonds.html"
mdcHorNav[5].subnav = new Array()
mdcHorNav[5].subnav[0] = new Object();
mdcHorNav[5].subnav[0].text = "Main: Overview, Intraday Quotes, Links to All Data";
mdcHorNav[5].subnav[0].href = "/mdc/public/page/mdc_bonds.html";
mdcHorNav[5].subnav[0].indent = 0;
mdcHorNav[5].subnav[0].style = "navmenupage";
mdcHorNav[5].subnav[0].changeBg = false;
mdcHorNav[5].subnav[1] = new Object();
mdcHorNav[5].subnav[1].text = "Benchmarks";
mdcHorNav[5].subnav[1].indent = 0;
mdcHorNav[5].subnav[1].style = "navmenusec";
mdcHorNav[5].subnav[2] = new Object();
mdcHorNav[5].subnav[2].text = "Bond & Index Benchmarks";
mdcHorNav[5].subnav[2].href = "/mdc/public/page/2_3022-bondbnchmrk.html";
mdcHorNav[5].subnav[2].indent = 0;
mdcHorNav[5].subnav[2].style = "navmenuitem";

mdcHorNav[5].subnav[3] = new Object();
mdcHorNav[5].subnav[3].text = "Libor";
mdcHorNav[5].subnav[3].href = "/mdc/public/page/2_3020-libor.html";
mdcHorNav[5].subnav[3].isHist = true;
mdcHorNav[5].subnav[3].indent = 0;
mdcHorNav[5].subnav[3].style = "navmenuitem";

mdcHorNav[5].subnav[4] = new Object();
mdcHorNav[5].subnav[4].text = "Euribor";
mdcHorNav[5].subnav[4].href = "/mdc/public/page/2_3020-euribor.html";
mdcHorNav[5].subnav[4].isHist = true;
mdcHorNav[5].subnav[4].indent = 0;
mdcHorNav[5].subnav[4].style = "navmenuitem";

mdcHorNav[5].subnav[5] = new Object();
mdcHorNav[5].subnav[5].text = "Money Rates";
mdcHorNav[5].subnav[5].href = "/mdc/public/page/2_3020-moneyrate.html";
mdcHorNav[5].subnav[5].isHist = true;
mdcHorNav[5].subnav[5].indent = 0;
mdcHorNav[5].subnav[5].style = "navmenuitem";
mdcHorNav[5].subnav[6] = new Object();
mdcHorNav[5].subnav[6].text = "Performance by Asset Class";
mdcHorNav[5].subnav[6].href = "/public/article/hotornot.html";
mdcHorNav[5].subnav[6].indent = 0;
mdcHorNav[5].subnav[6].style = "navmenuitem";
mdcHorNav[5].subnav[6].disabled = true;

mdcHorNav[5].subnav[7] = new Object();
mdcHorNav[5].subnav[7].text = "Ryan Bond Indexes";
mdcHorNav[5].subnav[7].href = "/mdc/public/page/2_3022-bondmkt.html";
mdcHorNav[5].subnav[7].indent = 0;
mdcHorNav[5].subnav[7].style = "navmenuitem";

mdcHorNav[5].subnav[8] = new Object();
mdcHorNav[5].subnav[8].text = "Quotes & Trading Statistics";
mdcHorNav[5].subnav[8].indent = 0;
mdcHorNav[5].subnav[8].style = "navmenusec";

mdcHorNav[5].subnav[9] = new Object();
mdcHorNav[5].subnav[9].text = "Bond Yields";
mdcHorNav[5].subnav[9].href = "/mdc/public/page/2_3021-bondyield.html";
mdcHorNav[5].subnav[9].indent = 0;
mdcHorNav[5].subnav[9].style = "navmenuitem";

mdcHorNav[5].subnav[10] = new Object();
mdcHorNav[5].subnav[10].text = "";
mdcHorNav[5].subnav[10].href = "/mdc/public/page/2_3027-corpbond.html";
mdcHorNav[5].subnav[10].indent = 0;
mdcHorNav[5].subnav[10].style = "navmenuitem";

mdcHorNav[5].subnav[11] = new Object();
mdcHorNav[5].subnav[11].text = "Corporate Gainers & Decliners";
mdcHorNav[5].subnav[11].href = "/mdc/public/page/2_3022-corpinvest.html";
mdcHorNav[5].subnav[11].indent = 0;
mdcHorNav[5].subnav[11].style = "navmenuitem";
mdcHorNav[5].subnav[12] = new Object();
mdcHorNav[5].subnav[12].text = "Credit Derivatives";
mdcHorNav[5].subnav[12].href = "/mdc/public/npage/2_3023_creditdervs.html";
mdcHorNav[5].subnav[12].indent = 0;
mdcHorNav[5].subnav[12].style = "navmenuitem";

mdcHorNav[5].subnav[13] = new Object();
mdcHorNav[5].subnav[13].text = "";
mdcHorNav[5].subnav[13].href = "";
mdcHorNav[5].subnav[13].indent = 0;
mdcHorNav[5].subnav[13].style = "navmenuitem";

mdcHorNav[5].subnav[14] = new Object();
mdcHorNav[5].subnav[14].text = "Government Agencies";
mdcHorNav[5].subnav[14].href = "/mdc/public/page/2_3020-govtagency.html";
mdcHorNav[5].subnav[14].indent = 0;
mdcHorNav[5].subnav[14].style = "navmenuitem";

mdcHorNav[5].subnav[15] = new Object();
mdcHorNav[5].subnav[15].text = "";
mdcHorNav[5].subnav[15].href = "/mdc/public/page/2_3024-gic.html";
mdcHorNav[5].subnav[15].indent = 0;
mdcHorNav[5].subnav[15].style = "navmenuitem";

mdcHorNav[5].subnav[16] = new Object();
mdcHorNav[5].subnav[16].text = "Mortgage-Backed Securities, CMOs";
mdcHorNav[5].subnav[16].href = "/mdc/public/page/2_3024-bondmbs.html";
mdcHorNav[5].subnav[16].indent = 0;
mdcHorNav[5].subnav[16].style = "navmenuitem";

mdcHorNav[5].subnav[17] = new Object();
mdcHorNav[5].subnav[17].text = "Syndicated Loan Market";
mdcHorNav[5].subnav[17].href = "/mdc/public/page/2_3021-syndloans.html";
mdcHorNav[5].subnav[17].indent = 0;
mdcHorNav[5].subnav[17].style = "navmenuitem";

mdcHorNav[5].subnav[18] = new Object();
mdcHorNav[5].subnav[18].text = "Tax-Exempt Bonds";
mdcHorNav[5].subnav[18].href = "/mdc/public/page/2_3024-bondbuyer.html";
mdcHorNav[5].subnav[18].indent = 0;
mdcHorNav[5].subnav[18].style = "navmenuitem";

mdcHorNav[5].subnav[19] = new Object();
mdcHorNav[5].subnav[19].text = "Treasury Inflation-Protected Securities (TIPS)";
mdcHorNav[5].subnav[19].href = "/mdc/public/page/2_3020-tips.html";
mdcHorNav[5].subnav[19].isHist = true;
mdcHorNav[5].subnav[19].indent = 0;
mdcHorNav[5].subnav[19].style = "navmenuitem";

mdcHorNav[5].subnav[20] = new Object();
mdcHorNav[5].subnav[20].text = "Treasury Quotes";
mdcHorNav[5].subnav[20].href = "/mdc/public/page/2_3020-treasury.html";
mdcHorNav[5].subnav[20].isHist = true;
mdcHorNav[5].subnav[20].indent = 0;
mdcHorNav[5].subnav[20].style = "navmenuitem";

mdcHorNav[5].subnav[21] = new Object();
mdcHorNav[5].subnav[21].text = "Treasury Strips";
mdcHorNav[5].subnav[21].href = "/mdc/public/page/2_3020-tstrips.html";
mdcHorNav[5].subnav[21].indent = 0;
mdcHorNav[5].subnav[21].style = "navmenuitem";

mdcHorNav[5].subnav[22] = new Object();
mdcHorNav[5].subnav[22].columnBreak = true;
mdcHorNav[5].subnav[23] = new Object();
mdcHorNav[5].subnav[23].text = "Mortgage & Banking Rates";
mdcHorNav[5].subnav[23].indent = 0;
mdcHorNav[5].subnav[23].style = "navmenusec";
mdcHorNav[5].subnav[24] = new Object();
mdcHorNav[5].subnav[24].text = "Main Page: Consumer Rates";
mdcHorNav[5].subnav[24].href = "http://www.bankrate.com/wsjl/rate/rate_center.asp";
mdcHorNav[5].subnav[24].indent = 0;
mdcHorNav[5].subnav[24].style = "navmenuitem";
mdcHorNav[5].subnav[25] = new Object();
mdcHorNav[5].subnav[25].text = "Find Local Mortgage Rates";
mdcHorNav[5].subnav[25].href = "http://www.bankrate.com/funnel/mortgages/?pid=p:wsj";
mdcHorNav[5].subnav[25].indent = 1;
mdcHorNav[5].subnav[25].style = "navmenuitem";
mdcHorNav[5].subnav[26] = new Object();
mdcHorNav[5].subnav[26].text = "Find Local Auto Loan Rates";
mdcHorNav[5].subnav[26].href = "http://www.bankrate.com/funnel/auto/?pid=p:wsj";
mdcHorNav[5].subnav[26].indent = 1;
mdcHorNav[5].subnav[26].style = "navmenuitem";
mdcHorNav[5].subnav[27] = new Object();
mdcHorNav[5].subnav[27].text = "Find Local IRA Rates";
mdcHorNav[5].subnav[27].href = "http://www.bankrate.com/funnel/cd-investments/?pid=p:wsj";
mdcHorNav[5].subnav[27].indent = 1;
mdcHorNav[5].subnav[27].style = "navmenuitem";
mdcHorNav[5].subnav[28] = new Object();
mdcHorNav[5].subnav[28].text = "Find Local Savings Rates";
mdcHorNav[5].subnav[28].href = "http://www.bankrate.com/funnel/savings/?pid=p:wsj";
mdcHorNav[5].subnav[28].indent = 1;
mdcHorNav[5].subnav[28].style = "navmenuitem";
mdcHorNav[5].subnav[29] = new Object();
mdcHorNav[5].subnav[29].text = "MMA, Savings & CD Rates";
mdcHorNav[5].subnav[29].href = "/mdc/public/page/2_3021-bankrate.html";
mdcHorNav[5].subnav[29].indent = 0;
mdcHorNav[5].subnav[29].style = "navmenuitem";

mdcHorNav[5].subnav[30] = new Object();
mdcHorNav[5].subnav[30].text = "New Issues";
mdcHorNav[5].subnav[30].indent = 0;
mdcHorNav[5].subnav[30].style = "navmenusec";
mdcHorNav[5].subnav[31] = new Object();
mdcHorNav[5].subnav[31].text = "Bond Offering Calendar";
mdcHorNav[5].subnav[31].href = "/mdc/public/page/2_3022-bondoffer.html";
mdcHorNav[5].subnav[31].indent = 0;
mdcHorNav[5].subnav[31].style = "navmenuitem";
mdcHorNav[5].subnav[32] = new Object();
mdcHorNav[5].subnav[32].text = "";
mdcHorNav[5].subnav[32].href = "";
mdcHorNav[5].subnav[32].indent = 0;
mdcHorNav[5].subnav[32].style = "";
mdcHorNav[5].subnav[33] = new Object();
mdcHorNav[5].subnav[33].text = "Shelf Registration Sales";
mdcHorNav[5].subnav[33].href = "/mdc/public/page/2_3023-offshelf.html";
mdcHorNav[5].subnav[33].indent = 0;
mdcHorNav[5].subnav[33].style = "navmenuitem";
mdcHorNav[5].subnav[34] = new Object();
mdcHorNav[5].subnav[34].text = "Government Data & the Fed";
mdcHorNav[5].subnav[34].indent = 0;
mdcHorNav[5].subnav[34].style = "navmenusec";

mdcHorNav[5].subnav[35] = new Object();
mdcHorNav[5].subnav[35].text = "";
mdcHorNav[5].subnav[35].href = "";
mdcHorNav[5].subnav[35].indent = 0;
mdcHorNav[5].subnav[35].style = "";

mdcHorNav[5].subnav[36] = new Object();
mdcHorNav[5].subnav[36].text = "Federal Reserve Monetary Data";
mdcHorNav[5].subnav[36].href = "/mdc/public/page/2_3022-fedresdata.html";
mdcHorNav[5].subnav[36].indent = 0;
mdcHorNav[5].subnav[36].style = "navmenuitem";

mdcHorNav[5].subnav[37] = new Object();
mdcHorNav[5].subnav[37].text = "";
mdcHorNav[5].subnav[37].href = "";
mdcHorNav[5].subnav[37].indent = 0;
mdcHorNav[5].subnav[37].style = "";

mdcHorNav[5].subnav[38] = new Object();
mdcHorNav[5].subnav[38].text = "Federal Interest Rates Report From IRS";
mdcHorNav[5].subnav[38].href = "/mdc/public/page/2_3024-fedrates.html";
mdcHorNav[5].subnav[38].indent = 0;
mdcHorNav[5].subnav[38].style = "navmenuitem";

mdcHorNav[5].subnav[39] = new Object();
mdcHorNav[5].subnav[39].text = "Key Interest Rates: Weekly Snapshot";
mdcHorNav[5].subnav[39].href = "/mdc/public/page/2_3020-keyinrates.html";
mdcHorNav[5].subnav[39].indent = 0;
mdcHorNav[5].subnav[39].style = "navmenuitem";

mdcHorNav[5].subnav[40] = new Object();
mdcHorNav[5].subnav[40].text = "International Credit Markets";
mdcHorNav[5].subnav[40].indent = 0;
mdcHorNav[5].subnav[40].style = "navmenusec";

mdcHorNav[5].subnav[41] = new Object();
mdcHorNav[5].subnav[41].text = "Global Government Bonds";
mdcHorNav[5].subnav[41].href = "/mdc/public/page/2_3022-govtbonds.html";
mdcHorNav[5].subnav[41].isHist = true;
mdcHorNav[5].subnav[41].indent = 0;
mdcHorNav[5].subnav[41].style = "navmenuitem";

mdcHorNav[6] = new Object()
mdcHorNav[6].pIDs = "|2_3012|"
mdcHorNav[6].name = "Commodities<br/>& Futures"
mdcHorNav[6].href = "/mdc/public/page/mdc_commodities.html"
mdcHorNav[6].subnav = new Array()
mdcHorNav[6].subnav[0] = new Object();
mdcHorNav[6].subnav[0].text = "Main: Overview, Intraday Quotes, Links to All Data";
mdcHorNav[6].subnav[0].href = "/mdc/public/page/mdc_commodities.html";
mdcHorNav[6].subnav[0].indent = 0;
mdcHorNav[6].subnav[0].style = "navmenupage";
mdcHorNav[6].subnav[0].changeBg = false;
mdcHorNav[6].subnav[1] = new Object();
mdcHorNav[6].subnav[1].text = "Intraday Futures Prices";
mdcHorNav[6].subnav[1].indent = 0;
mdcHorNav[6].subnav[1].style = "navmenusec";
mdcHorNav[6].subnav[2] = new Object();
mdcHorNav[6].subnav[2].text = "Agriculture";
mdcHorNav[6].subnav[2].indent = 0;
mdcHorNav[6].subnav[2].style = "navmenuitem";
mdcHorNav[6].subnav[3] = new Object();
mdcHorNav[6].subnav[3].text = "Food, Fiber";
mdcHorNav[6].subnav[3].href = "/mdc/public/page/2_3028.html";
mdcHorNav[6].subnav[3].indent = 1;
mdcHorNav[6].subnav[3].style = "navmenuitem";
mdcHorNav[6].subnav[4] = new Object();
mdcHorNav[6].subnav[4].text = "Livestock, Meat";
mdcHorNav[6].subnav[4].href = "/mdc/public/page/2_3028.html?category=Agriculture&subcategory=Livestock,%20Meat";
mdcHorNav[6].subnav[4].indent = 1;
mdcHorNav[6].subnav[4].style = "navmenuitem";
mdcHorNav[6].subnav[5] = new Object();
mdcHorNav[6].subnav[5].text = "Corn, Oats, Rice";
mdcHorNav[6].subnav[5].href = "/mdc/public/page/2_3028.html?category=Agriculture&subcategory=Corn,%20Oats,%20Rice";
mdcHorNav[6].subnav[5].indent = 1;
mdcHorNav[6].subnav[5].style = "navmenuitem";
mdcHorNav[6].subnav[6] = new Object();
mdcHorNav[6].subnav[6].text = "Oilseeds";
mdcHorNav[6].subnav[6].href = "/mdc/public/page/2_3028.html?category=Agriculture&subcategory=Oilseeds";
mdcHorNav[6].subnav[6].indent = 1;
mdcHorNav[6].subnav[6].style = "navmenuitem";
mdcHorNav[6].subnav[7] = new Object();
mdcHorNav[6].subnav[7].text = "Wheat";
mdcHorNav[6].subnav[7].href = "/mdc/public/page/2_3028.html?category=Agriculture&subcategory=Wheat";
mdcHorNav[6].subnav[7].indent = 1;
mdcHorNav[6].subnav[7].style = "navmenuitem";
mdcHorNav[6].subnav[8] = new Object();
mdcHorNav[6].subnav[8].text = "Ethanol";
mdcHorNav[6].subnav[8].href = "/mdc/public/page/2_3028.html?category=Agriculture&subcategory=Ethanol";
mdcHorNav[6].subnav[8].indent = 1;
mdcHorNav[6].subnav[8].style = "navmenuitem";
mdcHorNav[6].subnav[9] = new Object();
mdcHorNav[6].subnav[9].text = "Energy";
mdcHorNav[6].subnav[9].indent = 0;
mdcHorNav[6].subnav[9].style = "navmenuitem";
mdcHorNav[6].subnav[10] = new Object();
mdcHorNav[6].subnav[10].text = "Electricity";
mdcHorNav[6].subnav[10].href = "/mdc/public/page/2_3028.html?category=Energy&subcategory=Electricity";
mdcHorNav[6].subnav[10].indent = 1;
mdcHorNav[6].subnav[10].style = "navmenuitem";
mdcHorNav[6].subnav[11] = new Object();
mdcHorNav[6].subnav[11].text = "Petroleum";
mdcHorNav[6].subnav[11].href = "/mdc/public/page/2_3028.html?category=Energy&subcategory=Petroleum";
mdcHorNav[6].subnav[11].indent = 1;
mdcHorNav[6].subnav[11].style = "navmenuitem";
mdcHorNav[6].subnav[12] = new Object();
mdcHorNav[6].subnav[12].text = "Index";
mdcHorNav[6].subnav[12].indent = 0;
mdcHorNav[6].subnav[12].style = "navmenuitem";
mdcHorNav[6].subnav[13] = new Object();
mdcHorNav[6].subnav[13].text = "U.S.";
mdcHorNav[6].subnav[13].href = "/mdc/public/page/2_3028.html?category=Index&subcategory=U.S.";
mdcHorNav[6].subnav[13].indent = 1;
mdcHorNav[6].subnav[13].style = "navmenuitem";
mdcHorNav[6].subnav[14] = new Object();
mdcHorNav[6].subnav[14].text = "International";
mdcHorNav[6].subnav[14].href = "/mdc/public/page/2_3028.html?category=Index&subcategory=Non-U.S.";
mdcHorNav[6].subnav[14].indent = 1;
mdcHorNav[6].subnav[14].style = "navmenuitem";
mdcHorNav[6].subnav[15] = new Object();
mdcHorNav[6].subnav[15].text = "Interest Rate";
mdcHorNav[6].subnav[15].indent = 0;
mdcHorNav[6].subnav[15].style = "navmenuitem";
mdcHorNav[6].subnav[16] = new Object();
mdcHorNav[6].subnav[16].text = "Americas";
mdcHorNav[6].subnav[16].href = "/mdc/public/page/2_3028.html?category=Interest%2520Rate&subcategory=Americas";
mdcHorNav[6].subnav[16].indent = 1;
mdcHorNav[6].subnav[16].style = "navmenuitem";
mdcHorNav[6].subnav[17] = new Object();
mdcHorNav[6].subnav[17].text = "Europe";
mdcHorNav[6].subnav[17].href = "/mdc/public/page/2_3028.html?category=Interest%2520Rate&subcategory=Europe";
mdcHorNav[6].subnav[17].indent = 1;
mdcHorNav[6].subnav[17].style = "navmenuitem";
mdcHorNav[6].subnav[18] = new Object();
mdcHorNav[6].subnav[18].text = "Euro";
mdcHorNav[6].subnav[18].href = "/mdc/public/page/2_3028.html?category=Interest%2520Rate&subcategory=Euro";
mdcHorNav[6].subnav[18].indent = 1;
mdcHorNav[6].subnav[18].style = "navmenuitem";
mdcHorNav[6].subnav[19] = new Object();
mdcHorNav[6].subnav[19].text = "EuroDollar, Yen";
mdcHorNav[6].subnav[19].href = "/mdc/public/page/2_3028.html?category=Interest%2520Rate&subcategory=EuroDollar%2FYen";
mdcHorNav[6].subnav[19].indent = 1;
mdcHorNav[6].subnav[19].style = "navmenuitem";
mdcHorNav[6].subnav[20] = new Object();
mdcHorNav[6].subnav[20].text = "Asian, Pacific";
mdcHorNav[6].subnav[20].href = "/mdc/public/page/2_3028.html?category=Interest%2520Rate&subcategory=Asian%2FPacific";
mdcHorNav[6].subnav[20].indent = 1;
mdcHorNav[6].subnav[20].style = "navmenuitem";
mdcHorNav[6].subnav[21] = new Object();
mdcHorNav[6].subnav[21].text = "Metals";
mdcHorNav[6].subnav[21].indent = 0;
mdcHorNav[6].subnav[21].style = "navmenuitem";
mdcHorNav[6].subnav[22] = new Object();
mdcHorNav[6].subnav[22].text = "Copper";
mdcHorNav[6].subnav[22].href = "/mdc/public/page/2_3028.html?category=Other&subcategory=Metals&contract=Copper%252520Comp.%252520-%252520comex&catandsubcat=Other%257CMetals&contractset=Copper%252520Comp.%252520-%252520comex";
mdcHorNav[6].subnav[22].indent = 1;
mdcHorNav[6].subnav[22].style = "navmenuitem";
mdcHorNav[6].subnav[23] = new Object();
mdcHorNav[6].subnav[23].text = "Gold";
mdcHorNav[6].subnav[23].href = "/mdc/public/page/2_3028.html?category=Other&subcategory=Metals";
mdcHorNav[6].subnav[23].indent = 1;
mdcHorNav[6].subnav[23].style = "navmenuitem";
mdcHorNav[6].subnav[24] = new Object();
mdcHorNav[6].subnav[24].text = "Platinum";
mdcHorNav[6].subnav[24].href = "/mdc/public/page/2_3028.html?category=Other&subcategory=Metals&contract=Platinum%252520Comp.%252520-%252520nymex&catandsubcat=Other%257CMetals&contractset=Platinum%252520Comp.%252520-%252520nymex";
mdcHorNav[6].subnav[24].indent = 1;
mdcHorNav[6].subnav[24].style = "navmenuitem";
mdcHorNav[6].subnav[25] = new Object();
mdcHorNav[6].subnav[25].text = "Palladium";
mdcHorNav[6].subnav[25].href = "/mdc/public/page/2_3028.html?category=Other&subcategory=Metals&contract=Palladium%252520Comp.%252520-%252520comex&catandsubcat=Other%257CMetals&contractset=Palladium%252520Comp.%252520-%252520comex";
mdcHorNav[6].subnav[25].indent = 1;
mdcHorNav[6].subnav[25].style = "navmenuitem";
mdcHorNav[6].subnav[26] = new Object();
mdcHorNav[6].subnav[26].text = "Silver";
mdcHorNav[6].subnav[26].href = "/mdc/public/page/2_3028.html?category=Other&subcategory=Metals&contract=Silver%252520Comp.%252520-%252520comex&catandsubcat=Other%257CMetals&contractset=Silver%252520Comp.%252520-%252520comex";
mdcHorNav[6].subnav[26].indent = 1;
mdcHorNav[6].subnav[26].style = "navmenuitem";
mdcHorNav[6].subnav[27] = new Object();
mdcHorNav[6].subnav[27].text = "Other";
mdcHorNav[6].subnav[27].indent = 0;
mdcHorNav[6].subnav[27].style = "navmenuitem";
mdcHorNav[6].subnav[28] = new Object();
mdcHorNav[6].subnav[28].text = "Currency";
mdcHorNav[6].subnav[28].href = "/mdc/public/page/2_3028.html?category=Other&subcategory=Currency";
mdcHorNav[6].subnav[28].indent = 1;
mdcHorNav[6].subnav[28].style = "navmenuitem";
mdcHorNav[6].subnav[29] = new Object();
mdcHorNav[6].subnav[29].text = "Lumber";
mdcHorNav[6].subnav[29].href = "/mdc/public/page/2_3028.html?category=Other&subcategory=Lumber";
mdcHorNav[6].subnav[29].indent = 1;
mdcHorNav[6].subnav[29].style = "navmenuitem";
mdcHorNav[6].subnav[30] = new Object();
mdcHorNav[6].subnav[30].text = "Weather";
mdcHorNav[6].subnav[30].href = "/mdc/public/page/2_3028.html?category=Other&subcategory=Weather";
mdcHorNav[6].subnav[30].indent = 1;
mdcHorNav[6].subnav[30].style = "navmenuitem";
mdcHorNav[6].subnav[31] = new Object();
mdcHorNav[6].subnav[31].columnBreak = true;
mdcHorNav[6].subnav[32] = new Object();
mdcHorNav[6].subnav[32].text = "Spot Prices";
mdcHorNav[6].subnav[32].indent = 0;
mdcHorNav[6].subnav[32].style = "navmenusec";
mdcHorNav[6].subnav[33] = new Object();
mdcHorNav[6].subnav[33].text = "Cash Commodity Prices";
mdcHorNav[6].subnav[33].href = "/mdc/public/page/2_3023-cashprices.html";
mdcHorNav[6].subnav[33].isHist = true;
mdcHorNav[6].subnav[33].indent = 0;
mdcHorNav[6].subnav[33].style = "navmenuitem";
mdcHorNav[6].subnav[34] = new Object();
mdcHorNav[6].subnav[34].text = "";
mdcHorNav[6].subnav[34].href = "";
mdcHorNav[6].subnav[34].indent = 0;
mdcHorNav[6].subnav[34].style = "";

mdcHorNav[6].subnav[35] = new Object();
mdcHorNav[6].subnav[35].text = "Settlement Prices, Indexes & Other Statistics";
mdcHorNav[6].subnav[35].indent = 0;
mdcHorNav[6].subnav[35].style = "navmenusec";

mdcHorNav[6].subnav[36] = new Object();
mdcHorNav[6].subnav[36].text = "";
mdcHorNav[6].subnav[36].href = "";
mdcHorNav[6].subnav[36].isHist = true;
mdcHorNav[6].subnav[36].indent = 0;
mdcHorNav[6].subnav[36].style = "navmenuitem";

mdcHorNav[6].subnav[37] = new Object();
mdcHorNav[6].subnav[37].text = "Commodities Indexes";
mdcHorNav[6].subnav[37].href = "/mdc/public/page/2_3020-commodidx.html";
mdcHorNav[6].subnav[37].indent = 0;
mdcHorNav[6].subnav[37].style = "navmenuitem";

mdcHorNav[6].subnav[38] = new Object();
mdcHorNav[6].subnav[38].text = "";
mdcHorNav[6].subnav[38].href = "";
mdcHorNav[6].subnav[38].indent = 0;
mdcHorNav[6].subnav[38].style = "navmenuitem";

mdcHorNav[6].subnav[39] = new Object();
mdcHorNav[6].subnav[39].text = "";
mdcHorNav[6].subnav[39].href = "";
mdcHorNav[6].subnav[39].indent = 0;
mdcHorNav[6].subnav[39].style = "";

mdcHorNav[6].subnav[40] = new Object();
mdcHorNav[6].subnav[40].text = "Futures Settlements";
mdcHorNav[6].subnav[40].href = "/mdc/public/page/2_3023-fut_metal-futures.html";
mdcHorNav[6].subnav[40].isHist = true;
mdcHorNav[6].subnav[40].indent = 0;
mdcHorNav[6].subnav[40].style = "navmenuitem";

mdcHorNav[6].subnav[41] = new Object();
mdcHorNav[6].subnav[41].text = "London Metal Exchange Prices";
mdcHorNav[6].subnav[41].href = "/mdc/public/page/2_3021-londMetal.html";
mdcHorNav[6].subnav[41].indent = 0;
mdcHorNav[6].subnav[41].style = "navmenuitem";

mdcHorNav[6].subnav[42] = new Object();
mdcHorNav[6].subnav[42].text = "Performance by Asset Class: Weekly Snapshot";
mdcHorNav[6].subnav[42].href = "/public/article/hotornot.html";
mdcHorNav[6].subnav[42].indent = 0;
mdcHorNav[6].subnav[42].style = "navmenuitem";
mdcHorNav[6].subnav[42].disabled = true;



mdcHorNav[6].subnav[43] = new Object();
mdcHorNav[6].subnav[43].text = "";
mdcHorNav[6].subnav[43].indent = 0;
mdcHorNav[6].subnav[43].style = "navmenusec";
mdcHorNav[6].subnav[44] = new Object();
mdcHorNav[6].subnav[44].text = "";
mdcHorNav[6].subnav[44].href = "";
mdcHorNav[6].subnav[44].indent = 0;
mdcHorNav[6].subnav[44].style = "navmenuitem";
mdcHorNav[6].subnav[45] = new Object();
mdcHorNav[6].subnav[45].text = "";
mdcHorNav[6].subnav[45].href = "";
mdcHorNav[6].subnav[45].indent = 0;
mdcHorNav[6].subnav[45].style = "navmenuitem";
mdcHorNav[6].subnav[46] = new Object();
mdcHorNav[6].subnav[46].text = "";
mdcHorNav[6].subnav[46].href = "";
mdcHorNav[6].subnav[46].indent = 0;
mdcHorNav[6].subnav[46].style = "navmenuitem";
mdcHorNav[6].subnav[47] = new Object();
mdcHorNav[6].subnav[47].text = "";
mdcHorNav[6].subnav[47].href = "";
mdcHorNav[6].subnav[47].indent = 0;
mdcHorNav[6].subnav[47].style = "navmenuitem";
mdcHorNav[6].subnav[48] = new Object();
mdcHorNav[6].subnav[48].text = "";
mdcHorNav[6].subnav[48].href = "";
mdcHorNav[6].subnav[48].indent = 0;
mdcHorNav[6].subnav[48].style = "navmenuitem";
mdcHorNav[6].subnav[49] = new Object();
mdcHorNav[6].subnav[49].text = "";
mdcHorNav[6].subnav[49].href = "";
mdcHorNav[6].subnav[49].indent = 0;
mdcHorNav[6].subnav[49].style = "navmenuitem";
mdcHorNav[6].subnav[50] = new Object();
mdcHorNav[6].subnav[50].text = "";
mdcHorNav[6].subnav[50].href = "";
mdcHorNav[6].subnav[50].indent = 0;
mdcHorNav[6].subnav[50].style = "navmenuitem";


mdcHorNav[7] = new Object()
mdcHorNav[7].pIDs = "|2_3014|"
mdcHorNav[7].name = "Currencies"
mdcHorNav[7].href = "/mdc/public/page/mdc_currencies.html"
mdcHorNav[7].subnav = new Array()
mdcHorNav[7].subnav[0] = new Object();
mdcHorNav[7].subnav[0].text = "Main: Intraday Quotes, Links to All Data";
mdcHorNav[7].subnav[0].href = "/mdc/public/page/mdc_currencies.html";
mdcHorNav[7].subnav[0].indent = 0;
mdcHorNav[7].subnav[0].style = "navmenupage";
mdcHorNav[7].subnav[0].changeBg = false;
mdcHorNav[7].subnav[1] = new Object();
mdcHorNav[7].subnav[1].text = "Exchange Rates";
mdcHorNav[7].subnav[1].indent = 0;
mdcHorNav[7].subnav[1].style = "navmenusec";
mdcHorNav[7].subnav[2] = new Object();
mdcHorNav[7].subnav[2].text = "Hourly Snapshots";
mdcHorNav[7].subnav[2].href = "/mdc/public/page/2_3022-hourlyforex.html";
mdcHorNav[7].subnav[2].indent = 1;
mdcHorNav[7].subnav[2].style = "navmenuitem";
mdcHorNav[7].subnav[2].disabled = false;

mdcHorNav[7].subnav[3] = new Object();
mdcHorNav[7].subnav[3].text = "New York Closing";
mdcHorNav[7].subnav[3].href = "/mdc/public/page/2_3021-forex.html";
mdcHorNav[7].subnav[3].isHist = true;
mdcHorNav[7].subnav[3].hasCsv = true;
mdcHorNav[7].subnav[3].indent = 1;
mdcHorNav[7].subnav[3].style = "navmenuitem";
mdcHorNav[7].subnav[4] = new Object();
mdcHorNav[7].subnav[4].text = "Cross Rates: Closing Snapshot";
mdcHorNav[7].subnav[4].href = "/mdc/public/page/2_3023-keyrates.html";
mdcHorNav[7].subnav[4].isHist = true;
mdcHorNav[7].subnav[4].indent = 0;
mdcHorNav[7].subnav[4].style = "navmenuitem";
mdcHorNav[7].subnav[5] = new Object();
mdcHorNav[7].subnav[5].text = "Currency Futures: Intraday";
mdcHorNav[7].subnav[5].href = "/mdc/public/page/2_3028.html?category=Other&subcategory=Currency";
mdcHorNav[7].subnav[5].indent = 0;
mdcHorNav[7].subnav[5].style = "navmenuitem";
mdcHorNav[7].subnav[6] = new Object();
mdcHorNav[7].subnav[6].text = "Currency Futures Settlements";
mdcHorNav[7].subnav[6].href = "/mdc/public/page/2_3023-fut_currency-futures.html";
mdcHorNav[7].subnav[6].isHist = true;
mdcHorNav[7].subnav[6].indent = 0;
mdcHorNav[7].subnav[6].style = "navmenuitem";
mdcHorNav[7].subnav[7] = new Object();
mdcHorNav[7].subnav[7].text = "";
mdcHorNav[7].subnav[7].href = "";
mdcHorNav[7].subnav[7].indent = 0;
mdcHorNav[7].subnav[7].style = "navmenuitem";
mdcHorNav[7].subnav[8] = new Object();
mdcHorNav[7].subnav[8].text = "";
mdcHorNav[7].subnav[8].href = "";
mdcHorNav[7].subnav[8].indent = 0;
mdcHorNav[7].subnav[8].style = "navmenuitem";

mdcHorNav[8] = new Object()
mdcHorNav[8].pIDs = "|2_3016|"
mdcHorNav[8].name = "Calendars &<br/>Economy"
mdcHorNav[8].href = "/mdc/public/page/marketsdata.html#calandeco"
mdcHorNav[8].subnav = new Array()
mdcHorNav[8].subnav[0] = new Object();
mdcHorNav[8].subnav[0].text = "Calendars";
mdcHorNav[8].subnav[0].indent = 0;
mdcHorNav[8].subnav[0].style = "navmenusec";
mdcHorNav[8].subnav[0].changeBg = false;
mdcHorNav[8].subnav[1] = new Object();
mdcHorNav[8].subnav[1].text = "Bond Offerings";
mdcHorNav[8].subnav[1].href = "/mdc/public/page/2_3022-bondoffer.html";
mdcHorNav[8].subnav[1].indent = 0;
mdcHorNav[8].subnav[1].style = "navmenuitem";
mdcHorNav[8].subnav[2] = new Object();
mdcHorNav[8].subnav[2].text = "IPOs & Stock Offerings";
mdcHorNav[8].subnav[2].href = "/mdc/public/page/2_3022-newoffer.html";
mdcHorNav[8].subnav[2].indent = 0;
mdcHorNav[8].subnav[2].style = "navmenuitem";
mdcHorNav[8].subnav[3] = new Object();
mdcHorNav[8].subnav[3].text = "Earnings & Conference Calls";
mdcHorNav[8].subnav[3].href = "/public/Markets_Calendar.html";
mdcHorNav[8].subnav[3].indent = 0;
mdcHorNav[8].subnav[3].style = "navmenuitem";
mdcHorNav[8].subnav[3].disabled = true;
mdcHorNav[8].subnav[4] = new Object();
mdcHorNav[8].subnav[4].text = "International Economic Events";
mdcHorNav[8].subnav[4].href = "/mdc/public/page/2_3063-globalEconomicCalendar.html";
mdcHorNav[8].subnav[4].indent = 0;
mdcHorNav[8].subnav[4].style = "navmenuitem";
mdcHorNav[8].subnav[5] = new Object();
mdcHorNav[8].subnav[5].text = "U.S. Economic Events";
mdcHorNav[8].subnav[5].href = "/mdc/public/page/2_3063-economicCalendar.html";
mdcHorNav[8].subnav[5].indent = 0;
mdcHorNav[8].subnav[5].style = "navmenuitem";
mdcHorNav[8].subnav[6] = new Object();
mdcHorNav[8].subnav[6].text = "Economy";
mdcHorNav[8].subnav[6].indent = 0;
mdcHorNav[8].subnav[6].style = "navmenusec";
mdcHorNav[8].subnav[7] = new Object();
mdcHorNav[8].subnav[7].text = "Archive of Economic Indicators";
mdcHorNav[8].subnav[7].href = "/mdc/public/page/2_3024-indicate.html";
mdcHorNav[8].subnav[7].indent = 0;
mdcHorNav[8].subnav[7].style = "navmenuitem";
mdcHorNav[8].subnav[8] = new Object();
mdcHorNav[8].subnav[8].text = "Auto Sales";
mdcHorNav[8].subnav[8].href = "/mdc/public/page/2_3022-autosales.html";
mdcHorNav[8].subnav[8].indent = 0;
mdcHorNav[8].subnav[8].style = "navmenuitem";
mdcHorNav[8].subnav[9] = new Object();
mdcHorNav[8].subnav[9].text = "Charts of Key Economic Data";
mdcHorNav[8].subnav[9].href = "/mdc/public/page/2_3024-ecocharts.html";
mdcHorNav[8].subnav[9].indent = 0;
mdcHorNav[8].subnav[9].style = "navmenuitem";
mdcHorNav[8].subnav[10] = new Object();
mdcHorNav[8].subnav[10].text = "";
mdcHorNav[8].subnav[10].href = "";
mdcHorNav[8].subnav[10].indent = 0;
mdcHorNav[8].subnav[10].style = "";

mdcHorNav[8].subnav[11] = new Object();
mdcHorNav[8].subnav[11].text = "Patent Scorecard";
mdcHorNav[8].subnav[11].href = "/mdc/public/page/2_3022-macromkt.html";
mdcHorNav[8].subnav[11].indent = 0;
mdcHorNav[8].subnav[11].style = "navmenuitem";

mdcHorNav[8].subnav[12] = new Object();
mdcHorNav[8].subnav[12].text = "";
//mdcHorNav[8].subnav[12].href = "/mdc/public/page/2_3024-EconomicCalendar.html";
//mdcHorNav[8].subnav[12].indent = 0;
mdcHorNav[8].subnav[12].style = "";

mdcHorNav[8].subnav[13] = new Object();
mdcHorNav[8].subnav[13].text = "WSJ Economic Forecasting Survey";
mdcHorNav[8].subnav[13].href = "/economists";
mdcHorNav[8].subnav[13].indent = 0;
mdcHorNav[8].subnav[13].style = "navmenuitem";

mdcHorNav[9] = new Object()
mdcHorNav[9].pIDs = "|2_3018|"
mdcHorNav[9].name = "Earnings"
mdcHorNav[9].href = "/mdc/public/page/marketsdata.html#earnings"
mdcHorNav[9].subnav = new Array()
mdcHorNav[9].subnav[0] = new Object();
mdcHorNav[9].subnav[0].text = "Latest Data";
mdcHorNav[9].subnav[0].indent = 0;
mdcHorNav[9].subnav[0].style = "navmenusec";
mdcHorNav[9].subnav[0].changeBg = false;
mdcHorNav[9].subnav[1] = new Object();
mdcHorNav[9].subnav[1].text = "Earnings Calendar";
mdcHorNav[9].subnav[1].href = "/public/Markets_Calendar.html";
mdcHorNav[9].subnav[1].indent = 0;
mdcHorNav[9].subnav[1].style = "navmenuitem";
mdcHorNav[9].subnav[1].disabled = true;
//mdcHorNav[9].subnav[2] = new Object();
//mdcHorNav[9].subnav[2].text = "Earnings Digest: Summary of Latest Reports";
//mdcHorNav[9].subnav[2].href = "/mdc/public/page/2_3024-//digest_earnings.html";
//mdcHorNav[9].subnav[2].indent = 0;
//mdcHorNav[9].subnav[2].style = "navmenuitem";
mdcHorNav[9].subnav[2] = new Object();
mdcHorNav[9].subnav[2].text = "Earnings Surprises";
mdcHorNav[9].subnav[2].href = "/mdc/public/page/2_3024-zurprise.html";
mdcHorNav[9].subnav[2].indent = 0;
mdcHorNav[9].subnav[2].style = "navmenuitem";
mdcHorNav[9].subnav[3] = new Object();
mdcHorNav[9].subnav[3].text = "Historical Data";
mdcHorNav[9].subnav[3].indent = 0;
mdcHorNav[9].subnav[3].style = "navmenusec";
mdcHorNav[9].subnav[4] = new Object();
mdcHorNav[9].subnav[4].text = "Company Research: Financials";
mdcHorNav[9].subnav[4].href = "/redirect/companyresearch.html";
mdcHorNav[9].subnav[4].indent = 0;
mdcHorNav[9].subnav[4].style = "navmenuitem";
